const suggestions = [
  { label: "A.R.C. Commander Arm Guards (L)", tt: 100 },
  { label: "A.R.C. Commander Cap (L)", tt: 100 },
  { label: "A.R.C. Commander Chest Guard (L)", tt: 100 },
  { label: "A.R.C. Commander Foot Guards (L)", tt: 100 },
  { label: "A.R.C. Commander Hand Guards (L)", tt: 100 },
  { label: "A.R.C. Commander Leg Guards (L)", tt: 100 },
  { label: "A.R.C. Commander Shin Guards (L)", tt: 100 },
  { label: "A.R.C. Elite Arm Guards (L)", tt: 85 },
  { label: "A.R.C. Elite Foot Guards", tt: 60 },
  { label: "A.R.C. Elite Hand Guards (L)", tt: 85 },
  { label: "A.R.C. Elite Shin Guards (L)", tt: 85 },
  { label: "A.R.C. Elite Thigh Guards (L)", tt: 85 },
  { label: "A.R.C. Guardian Arm Guards", tt: 4 },
  { label: "A.R.C. Guardian Foot Guards", tt: 4 },
  { label: "A.R.C. Guardian Hand Guards", tt: 4 },
  { label: "A.R.C. Guardian Harness", tt: 4 },
  { label: "A.R.C. Guardian Helmet", tt: 4 },
  { label: "A.R.C. Guardian Shin Guards", tt: 4 },
  { label: "A.R.C. Guardian Thigh Guards", tt: 4 },
  { label: "A.R.C. Hazard Foot Guards (L)", tt: 60 },
  { label: "A.R.C. Hazard Hand Guards (L)", tt: 85 },
  { label: "A.R.C. Hazard Head Guard (L)", tt: 100 },
  { label: "A.R.C. Hazard Thigh Guards (L)", tt: 85 },
  { label: "A.R.C. Inaugurates Arm Guards (L)", tt: 28 },
  { label: "A.R.C. Inaugurates Cap (L)", tt: 30 },
  { label: "A.R.C. Inaugurates Chest Guard (L)", tt: 30 },
  { label: "A.R.C. Inaugurates Foot Guards (L)", tt: 28 },
  { label: "A.R.C. Inaugurates Hand Guards (L)", tt: 28 },
  { label: "A.R.C. Inaugurates Shin Guards (L)", tt: 28 },
  { label: "A.R.C. Inaugurates Thigh Guards (L)", tt: 28 },
  { label: "A.R.C. Patrol Arm Guards (L)", tt: 50 },
  { label: "A.R.C. Patrol Cap (L)", tt: 55 },
  { label: "A.R.C. Patrol Chest Guard (L)", tt: 55 },
  { label: "A.R.C. Patrol Foot Guards (L)", tt: 50 },
  { label: "A.R.C. Patrol Hand Guards (L)", tt: 50 },
  { label: "A.R.C. Patrol Shin Guards (L)", tt: 50 },
  { label: "A.R.C. Patrol Thigh Guards (L)", tt: 50 },
  { label: "A.R.C. Pilot Arm Guards", tt: 4.5 },
  { label: "A.R.C. Pilot Boots", tt: 4 },
  { label: "A.R.C. Pilot Gloves", tt: 3 },
  { label: "A.R.C. Pilot Harness", tt: 6 },
  { label: "A.R.C. Pilot Helmet", tt: 5 },
  { label: "A.R.C. Pilot Shin Guards", tt: 3.2 },
  { label: "A.R.C. Pilot Thigh Guards", tt: 4.3 },
  { label: "A.R.C. Ranger Arm Guards", tt: 14.2 },
  { label: "A.R.C. Ranger Boots", tt: 14.2 },
  { label: "A.R.C. Ranger Gloves", tt: 14.2 },
  { label: "A.R.C. Ranger Harness", tt: 14.2 },
  { label: "A.R.C. Ranger Helmet", tt: 14.2 },
  { label: "A.R.C. Ranger Leg Guards", tt: 14.2 },
  { label: "A.R.C. Ranger Shin Guards", tt: 14.2 },
  { label: "A.R.C. Special Ops Arm Guards (L)", tt: 28.5 },
  { label: "A.R.C. Special Ops Boots (L)", tt: 28.5 },
  { label: "A.R.C. Special Ops Gloves (L)", tt: 28.5 },
  { label: "A.R.C. Special Ops Harness (L)", tt: 28.5 },
  { label: "A.R.C. Special Ops Helmet (L)", tt: 28.5 },
  { label: "A.R.C. Special Ops Shin Guards (L)", tt: 28.5 },
  { label: "Angel Arm Guards", tt: 66 },
  { label: "Angel Arm Guards (L)", tt: 66 },
  { label: "Angel Arm Guards, SGA Edition", tt: 66 },
  { label: "Angel Arm Guards Adjusted", tt: 66 },
  { label: "Angel Arm Guards Improved", tt: 99 },
  { label: "Angel Foot Guards", tt: 33 },
  { label: "Angel Foot Guards (L)", tt: 33 },
  { label: "Angel Foot Guards, SGA Edition", tt: 33 },
  { label: "Angel Foot Guards Adjusted", tt: 33 },
  { label: "Angel Foot Guards Improved", tt: 49.5 },
  { label: "Angel Gloves", tt: 33 },
  { label: "Angel Gloves (L)", tt: 33 },
  { label: "Angel Gloves, SGA Edition", tt: 33 },
  { label: "Angel Gloves Adjusted", tt: 33 },
  { label: "Angel Gloves Improved", tt: 49.5 },
  { label: "Angel Gloves Modified", tt: 58 },
  { label: "Angel Harness", tt: 99 },
  { label: "Angel Harness (L)", tt: 99 },
  { label: "Angel Harness, SGA Edition", tt: 99 },
  { label: "Angel Harness Adjusted", tt: 99 },
  { label: "Angel Harness Improved", tt: 148.5 },
  { label: "Angel Harness Modified", tt: 175 },
  { label: "Angel Helmet", tt: 33 },
  { label: "Angel Helmet (L)", tt: 33 },
  { label: "Angel Helmet, SGA Edition", tt: 33 },
  { label: "Angel Helmet Adjusted", tt: 33 },
  { label: "Angel Helmet Improved", tt: 49.5 },
  { label: "Angel Helmet Modified", tt: 58 },
  { label: "Angel Shin Guards", tt: 33 },
  { label: "Angel Shin Guards (L)", tt: 33 },
  { label: "Angel Shin Guards, SGA Edition", tt: 33 },
  { label: "Angel Shin Guards Adjusted", tt: 33 },
  { label: "Angel Shin Guards Improved", tt: 49.5 },
  { label: "Angel Shin Guards Modified", tt: 58 },
  { label: "Angel Thigh Guards", tt: 66 },
  { label: "Angel Thigh Guards (L)", tt: 66 },
  { label: "Angel Thigh Guards, SGA Edition", tt: 66 },
  { label: "Angel Thigh Guards Adjusted", tt: 66 },
  { label: "Angel Thigh Guards Improved", tt: 99 },
  { label: "Angel Thigh Guards Modified", tt: 116 },
  { label: "Ankitus Arm Guards", tt: 4.2 },
  { label: "Ankitus Foot Guards", tt: 3.6 },
  { label: "Ankitus Gloves", tt: 3 },
  { label: "Ankitus Harness", tt: 7.2 },
  { label: "Ankitus Helmet", tt: 3.9 },
  { label: "Ankitus Shin Guards", tt: 3.9 },
  { label: "Ankitus Thigh Guards", tt: 4.2 },
  { label: "Anti Virus Arm Guards (L)", tt: 250 },
  { label: "Anti Virus Foot Guards (L)", tt: 125 },
  { label: "Anti Virus Gloves (L)", tt: 125 },
  { label: "Anti Virus Harness (L)", tt: 375 },
  { label: "Anti Virus Helmet (L)", tt: 125 },
  { label: "Anti Virus Shin Guards (L)", tt: 125 },
  { label: "Anti Virus Thigh Guards (L)", tt: 250 },
  { label: "Aquila Arm Guards", tt: 120 },
  { label: "Aquila Arm Guards (L)", tt: 112 },
  { label: "Aquila Foot Guards", tt: 88 },
  { label: "Aquila Foot Guards (L)", tt: 96 },
  { label: "Aquila Gloves", tt: 72 },
  { label: "Aquila Gloves (L)", tt: 80 },
  { label: "Aquila Harness", tt: 192 },
  { label: "Aquila Harness (L)", tt: 192 },
  { label: "Aquila Helmet", tt: 104 },
  { label: "Aquila Helmet (L)", tt: 104 },
  { label: "Aquila Shin Guards", tt: 112 },
  { label: "Aquila Shin Guards (L)", tt: 104 },
  { label: "Aquila Thigh Guards", tt: 112 },
  { label: "Aquila Thigh Guards (L)", tt: 112 },
  { label: "Arctic Arm Guards (L)", tt: 3.7 },
  { label: "Arctic Bullet Proof Vest (L)", tt: 5.55 },
  { label: "Arctic Face Guard (L)", tt: 1.85 },
  { label: "Arctic Foot Guards (L)", tt: 1.85 },
  { label: "Arctic Gloves (L)", tt: 1.85 },
  { label: "Arctic Shin Guards (L)", tt: 1.85 },
  { label: "Arctic Thigh Guard (L)", tt: 3.7 },
  { label: "Arm Guards of the Wormslayer", tt: 153 },
  { label: "Aurora Arm Guards (L)", tt: 52.5 },
  { label: "Aurora Foot Guards (L)", tt: 52.5 },
  { label: "Aurora Gloves (L)", tt: 52.5 },
  { label: "Aurora Harness (L)", tt: 90 },
  { label: "Aurora Helmet (L)", tt: 46 },
  { label: "Aurora Shin Guards (L)", tt: 45 },
  { label: "Aurora Thigh Guards (L)", tt: 52.5 },
  { label: "B.E. Arm Guards Improved", tt: 11.4 },
  { label: "B.E. Chest Guard Improved", tt: 11.4 },
  { label: "B.E. Foot Guards Improved", tt: 11.4 },
  { label: "B.E. Hand Guards Improved", tt: 11.4 },
  { label: "B.E. Head Guard Improved", tt: 11.4 },
  { label: "B.E. Leg Guards Improved", tt: 11.4 },
  { label: "B.E. Pilot Arm Guards", tt: 5.7 },
  { label: "B.E. Pilot Boots", tt: 5.7 },
  { label: "B.E. Pilot Gloves", tt: 5.7 },
  { label: "B.E. Pilot Harness", tt: 5.7 },
  { label: "B.E. Pilot Helmet", tt: 5.7 },
  { label: "B.E. Pilot Leg Guards", tt: 5.7 },
  { label: "B.E. Pilot Shin Guards", tt: 5.7 },
  { label: "B.E. Shin Guards Improved", tt: 11.4 },
  { label: "Basic Colonial Arm Guards (L)", tt: 3.2 },
  { label: "Basic Colonial Face Guard (L)", tt: 2.8 },
  { label: "Basic Colonial Foot Guards (L)", tt: 1.8 },
  { label: "Basic Colonial Gloves (L)", tt: 1.8 },
  { label: "Basic Colonial Harness (L)", tt: 4.4 },
  { label: "Basic Colonial Shin Guards (L)", tt: 2.8 },
  { label: "Basic Colonial Thigh Guards (L)", tt: 3.2 },
  { label: "Bear Arm Guards", tt: 63 },
  { label: "Bear Arm Guards (L)", tt: 63 },
  { label: "Bear Foot Guards", tt: 55 },
  { label: "Bear Foot Guards (L)", tt: 55 },
  { label: "Bear Gloves", tt: 55 },
  { label: "Bear Gloves (L)", tt: 55 },
  { label: "Bear Harness", tt: 130 },
  { label: "Bear Harness (L)", tt: 130 },
  { label: "Bear Helmet", tt: 59 },
  { label: "Bear Helmet (L)", tt: 59 },
  { label: "Bear Shin Guards", tt: 68 },
  { label: "Bear Shin Guards (L)", tt: 68 },
  { label: "Bear Thigh Guards", tt: 72 },
  { label: "Bear Thigh Guards (L)", tt: 72 },
  { label: "Bedaya Armor Arm Guards (L)", tt: 7.75 },
  { label: "Bedaya Armor Foot Guards (L)", tt: 4.25 },
  { label: "Bedaya Armor Harness (L)", tt: 10.5 },
  { label: "Bedaya Armor Helmet (L)", tt: 6.75 },
  { label: "Bedaya Armor Shin Guards (L)", tt: 6.75 },
  { label: "Bedaya Armor Thigh Guards (L)", tt: 7.75 },
  { label: "Berserker Arm Guards", tt: 19 },
  { label: "Berserker Face Guard", tt: 12 },
  { label: "Berserker Foot Guards", tt: 15 },
  { label: "Berserker Gloves", tt: 15 },
  { label: "Berserker Harness", tt: 30 },
  { label: "Berserker Shin Guards", tt: 13 },
  { label: "Berserker Thigh Guards", tt: 18 },
  { label: "Boar Arm Guards", tt: 67 },
  { label: "Boar Arm Guards (L)", tt: 67 },
  { label: "Boar Arm Guards, SGA Edition", tt: 67 },
  { label: "Boar Arm Guards Adjusted", tt: 67 },
  { label: "Boar Foot Guards", tt: 59 },
  { label: "Boar Foot Guards (L)", tt: 59 },
  { label: "Boar Foot Guards, SGA Edition", tt: 59 },
  { label: "Boar Foot Guards Adjusted", tt: 59 },
  { label: "Boar Gloves", tt: 59 },
  { label: "Boar Gloves (L)", tt: 59 },
  { label: "Boar Gloves, SGA Edition", tt: 59 },
  { label: "Boar Gloves Adjusted", tt: 59 },
  { label: "Boar Harness", tt: 149 },
  { label: "Boar Harness (L)", tt: 149 },
  { label: "Boar Harness, SGA Edition", tt: 149 },
  { label: "Boar Harness Adjusted", tt: 149 },
  { label: "Boar Helmet", tt: 64.5 },
  { label: "Boar Helmet (L)", tt: 64.5 },
  { label: "Boar Helmet, SGA Edition", tt: 64.5 },
  { label: "Boar Helmet Adjusted", tt: 64.5 },
  { label: "Boar Shin Guards", tt: 72.3 },
  { label: "Boar Shin Guards (L)", tt: 72.3 },
  { label: "Boar Shin Guards, SGA Edition", tt: 72.3 },
  { label: "Boar Shin Guards Adjusted", tt: 72.3 },
  { label: "Boar Thigh Guards", tt: 79.7 },
  { label: "Boar Thigh Guards (L)", tt: 79.7 },
  { label: "Boar Thigh Guards, SGA Edition", tt: 79.7 },
  { label: "Boar Thigh Guards Adjusted", tt: 79.7 },
  { label: "BodyGuard Arm Guards", tt: 6.5 },
  { label: "BodyGuard Arm Guards (L)", tt: 6.5 },
  { label: "BodyGuard Face Guard", tt: 4.3 },
  { label: "BodyGuard Face Guard (L)", tt: 4.3 },
  { label: "BodyGuard Foot Guards", tt: 4 },
  { label: "BodyGuard Foot Guards (L)", tt: 4 },
  { label: "BodyGuard Gloves", tt: 4 },
  { label: "BodyGuard Gloves (L)", tt: 4 },
  { label: "BodyGuard Harness", tt: 9 },
  { label: "BodyGuard Harness (L)", tt: 9 },
  { label: "BodyGuard Shin Guards", tt: 4.5 },
  { label: "BodyGuard Shin Guards (L)", tt: 4.5 },
  { label: "BodyGuard Thigh Guards", tt: 6.3 },
  { label: "BodyGuard Thigh Guards (L)", tt: 6.3 },
  { label: "Canis Arm Guards", tt: 18 },
  { label: "Canis Arm Guards (L)", tt: 16.8 },
  { label: "Canis Foot Guards", tt: 13.2 },
  { label: "Canis Foot Guards (L)", tt: 14.4 },
  { label: "Canis Gloves", tt: 10.8 },
  { label: "Canis Gloves (L)", tt: 12 },
  { label: "Canis Harness", tt: 28.8 },
  { label: "Canis Harness (L)", tt: 28.8 },
  { label: "Canis Helmet", tt: 15.6 },
  { label: "Canis Helmet (L)", tt: 15.6 },
  { label: "Canis Shin Guards", tt: 16.8 },
  { label: "Canis Shin Guards (L)", tt: 15.6 },
  { label: "Canis Thigh Guards", tt: 16.8 },
  { label: "Canis Thigh Guards (L)", tt: 16.8 },
  { label: "Carapace Communications Helmet (L)", tt: 0.26 },
  { label: "Carapace Vest (L)", tt: 0.48 },
  { label: "Carramone Arm Guards", tt: 280 },
  { label: "Carramone Foot Guards", tt: 490 },
  { label: "Carramone Gloves", tt: 490 },
  { label: "Carramone Harness", tt: 480 },
  { label: "Carramone Helmet", tt: 350 },
  { label: "Carramone Shin Guards", tt: 390 },
  { label: "Carramone Thigh Guards", tt: 370 },
  { label: "CDF Scout Arm Guards", tt: 2.3 },
  { label: "CDF Scout Face Guard", tt: 1.8 },
  { label: "CDF Scout Foot Guards", tt: 1.6 },
  { label: "CDF Scout Gloves", tt: 1.6 },
  { label: "CDF Scout Harness", tt: 3.2 },
  { label: "CDF Scout Shin Guards", tt: 1.7 },
  { label: "CDF Scout Thigh Guards", tt: 2.3 },
  { label: "Cetus Arm Guards", tt: 75 },
  { label: "Cetus Arm Guards (L)", tt: 70 },
  { label: "Cetus Foot", tt: 55 },
  { label: "Cetus Foot Guards (L)", tt: 60 },
  { label: "Cetus Gloves", tt: 45 },
  { label: "Cetus Gloves (L)", tt: 50 },
  { label: "Cetus Harness", tt: 120 },
  { label: "Cetus Harness (L)", tt: 120 },
  { label: "Cetus Helmet", tt: 65 },
  { label: "Cetus Helmet (L)", tt: 65 },
  { label: "Cetus Shin Guards", tt: 70 },
  { label: "Cetus Shin Guards (L)", tt: 65 },
  { label: "Cetus Thigh Guards", tt: 70 },
  { label: "Cetus Thigh Guards (L)", tt: 70 },
  { label: "Chameleon Mk2 Arm Guards (L)", tt: 50 },
  { label: "Chameleon Mk2 Gloves (L)", tt: 35 },
  { label: "Chameleon Mk2 Groin Guard (L)", tt: 62 },
  { label: "Chameleon Mk2 Shoulder Guard (L)", tt: 69 },
  { label: "Cheap A$$ Arm Guards (C)", tt: 3.7 },
  { label: "Cheap A$$ Face Guard (C)", tt: 1.85 },
  { label: "Cheap A$$ Foot Guards (C)", tt: 1.85 },
  { label: "Cheap A$$ Gloves (C)", tt: 1.85 },
  { label: "Cheap A$$ Harness (C)", tt: 5.55 },
  { label: "Cheap A$$ Shin Guards (C)", tt: 1.85 },
  { label: "Cheap A$$ Thigh Guards (C)", tt: 3.7 },
  { label: "Chelydra Arm Guards", tt: 86 },
  { label: "Chelydra Foot Guards", tt: 66 },
  { label: "Chelydra Gloves", tt: 66 },
  { label: "Chelydra Harness", tt: 115 },
  { label: "Chelydra Helmet", tt: 86 },
  { label: "Chelydra Shin Guards", tt: 75 },
  { label: "Chelydra Thigh Guards", tt: 97 },
  { label: "Chromatophore Mk2 Arm Guards (C,L)", tt: 50 },
  { label: "Chromatophore Mk2 Foot Guards (C,L)", tt: 37 },
  { label: "Chromatophore Mk2 Gloves (C,L)", tt: 35 },
  { label: "Chromatophore Mk2 Groin Guard (C,L)", tt: 62 },
  { label: "Chromatophore Mk2 Shoulder Guards (C,L)", tt: 69 },
  { label: "Chromatophore Mk.I Arm Guards (C,L)", tt: 26 },
  { label: "Chromatophore Mk.I Face Guard (C,L)", tt: 32 },
  { label: "Chromatophore Mk.I Foot Guards (C,L)", tt: 17.5 },
  { label: "Chromatophore Mk.I Gloves (C,L)", tt: 18.5 },
  { label: "Chromatophore Mk.I Harness (C,L)", tt: 35 },
  { label: "Chromatophore Mk.I Shin Guards (C,L)", tt: 25 },
  { label: "Chromatophore Mk.I Thigh Guards (C,L)", tt: 31 },
  { label: "Chronicle Arm Guards", tt: 250 },
  { label: "Chronicle Arm Guards (L)", tt: 250 },
  { label: "Chronicle Arm Guards TEN Edition", tt: 284 },
  { label: "Chronicle Foot Guards", tt: 216 },
  { label: "Chronicle Foot Guards (L)", tt: 216 },
  { label: "Chronicle Foot Guards TEN Edition", tt: 246 },
  { label: "Chronicle Gloves", tt: 125 },
  { label: "Chronicle Gloves (L)", tt: 125 },
  { label: "Chronicle Gloves TEN Edition", tt: 246 },
  { label: "Chronicle Harness", tt: 360 },
  { label: "Chronicle Harness (L)", tt: 360 },
  { label: "Chronicle Harness TEN Edition", tt: 409 },
  { label: "Chronicle Helmet", tt: 200 },
  { label: "Chronicle Helmet (L)", tt: 200 },
  { label: "Chronicle Helmet TEN Edition", tt: 228 },
  { label: "Chronicle Shin Guards", tt: 230 },
  { label: "Chronicle Shin Guards (L)", tt: 230 },
  { label: "Chronicle Shin Guards TEN Edition", tt: 262 },
  { label: "Chronicle Thigh Guards", tt: 240 },
  { label: "Chronicle Thigh Guards (L)", tt: 240 },
  { label: "Chronicle Thigh Guards TEN Edition", tt: 273 },
  { label: "Colonizer Arm Guards (L)", tt: 3.5 },
  { label: "Colonizer Face Guard (L)", tt: 2 },
  { label: "Colonizer Foot Guards (L)", tt: 1.9 },
  { label: "Colonizer Gloves (L)", tt: 1.9 },
  { label: "Colonizer Harness (L)", tt: 6 },
  { label: "Colonizer Shin Guards (L)", tt: 1.9 },
  { label: "Colonizer Thigh Guards (L)", tt: 3.1 },
  { label: "Community Recognition Award Arm Guards", tt: 73 },
  { label: "Community Recognition Award Foot Guards", tt: 66 },
  { label: "Community Recognition Award Gloves", tt: 66 },
  { label: "Community Recognition Award Harness", tt: 167.4 },
  { label: "Community Recognition Award Helmet", tt: 71.7 },
  { label: "Community Recognition Award Shin Guards", tt: 78.9 },
  { label: "Community Recognition Award Thighs Guards", tt: 83.4 },
  { label: "Corvus Arm Guards", tt: 9 },
  { label: "Corvus Arm Guards (L)", tt: 8.4 },
  { label: "Corvus Foot Guards", tt: 6.6 },
  { label: "Corvus Foot Guards (L)", tt: 7.2 },
  { label: "Corvus Gloves", tt: 5.4 },
  { label: "Corvus Gloves (L)", tt: 6 },
  { label: "Corvus Harness", tt: 14.4 },
  { label: "Corvus Harness (L)", tt: 14.4 },
  { label: "Corvus Helmet", tt: 7.8 },
  { label: "Corvus Helmet (L)", tt: 7.8 },
  { label: "Corvus Shin Guards", tt: 8.4 },
  { label: "Corvus Shin Guards (L)", tt: 7.8 },
  { label: "Corvus Thigh Guards", tt: 8.4 },
  { label: "Corvus Thigh Guards (L)", tt: 8.4 },
  { label: "Dark Knight of Arkadia (official) Foot Guards", tt: 10 },
  { label: "Dark Knight of Arkadia Arm Guards", tt: 298 },
  { label: "Dark Knight of Arkadia Foot Guards", tt: 287 },
  { label: "Dark Knight of Arkadia Gloves", tt: 287 },
  { label: "Dark Knight of Arkadia Harness", tt: 354 },
  { label: "Dark Knight of Arkadia Helmet", tt: 298 },
  { label: "Dark Knight of Arkadia Shin Guards", tt: 311 },
  { label: "Dark Knight of Arkadia Thigh Guards", tt: 309 },
  { label: "Deathbringer's Crown", tt: 102 },
  { label: "Disco Arm Guards (L)", tt: 73 },
  { label: "Disco Foot Guards (L)", tt: 66 },
  { label: "Disco Gloves (L)", tt: 66 },
  { label: "Disco Harness (L)", tt: 167.4 },
  { label: "Disco Helmet (L)", tt: 71.7 },
  { label: "Disco Shin Guards (L)", tt: 78.9 },
  { label: "Disco Thigh Guards (L)", tt: 83.4 },
  { label: "Dragon Arm Guards", tt: 14 },
  { label: "Dragon Face Guard", tt: 7 },
  { label: "Dragon Foot Guards", tt: 7 },
  { label: "Dragon Gloves", tt: 7 },
  { label: "Dragon Harness", tt: 21 },
  { label: "Dragon Shin Guards", tt: 7 },
  { label: "Dragon Thigh Guards", tt: 14 },
  { label: "DSEC Scout Harness", tt: 3.2 },
  { label: "Dune Rider Arm Guards", tt: 104 },
  { label: "Dune Rider Foot Guards", tt: 99 },
  { label: "Dune Rider Gloves", tt: 99 },
  { label: "Dune Rider Harness", tt: 135 },
  { label: "Dune Rider Helmet", tt: 61 },
  { label: "Dune Rider Shin Guards", tt: 100 },
  { label: "Dune Rider Thigh Guards", tt: 106 },
  { label: "Earth Shock Trooper Arm Guards (L)", tt: 48 },
  { label: "Earth Shock Trooper Foot Guards (L)", tt: 27 },
  { label: "Earth Shock Trooper Gloves (L)", tt: 27 },
  { label: "Earth Shock Trooper Harness (L)", tt: 66 },
  { label: "Earth Shock Trooper Helmet (L)", tt: 42 },
  { label: "Earth Shock Trooper Shin Guards (L)", tt: 42 },
  { label: "Earth Shock Trooper Thigh Guards (L)", tt: 48 },
  { label: "eMINE PG/A", tt: 36 },
  { label: "eMINE PG/A (L)", tt: 36 },
  { label: "eMINE PG/FG", tt: 35.5 },
  { label: "eMINE PG/FG (L)", tt: 35.5 },
  { label: "eMINE PG/G", tt: 34 },
  { label: "eMINE PG/G (L)", tt: 34 },
  { label: "eMINE PG/H", tt: 38.5 },
  { label: "eMINE PG/H (L)", tt: 38.5 },
  { label: "eMINE PG/HG", tt: 36 },
  { label: "eMINE PG/HG (L)", tt: 36 },
  { label: "eMINE PG/SG", tt: 35.5 },
  { label: "eMINE PG/SG (L)", tt: 35.5 },
  { label: "eMINE PG/T", tt: 59 },
  { label: "eMINE PG/T (L)", tt: 59 },
  { label: "Eon Arm Guards", tt: 210 },
  { label: "Eon Arm Guards (L)", tt: 210 },
  { label: "Eon Arm Guards, SGA Edition", tt: 210 },
  { label: "Eon Foot Guards", tt: 145 },
  { label: "Eon Foot Guards (L)", tt: 145 },
  { label: "Eon Foot Guards, SGA Edition", tt: 145 },
  { label: "Eon Gloves", tt: 145 },
  { label: "Eon Gloves (L)", tt: 145 },
  { label: "Eon Gloves, SGA Edition", tt: 145 },
  { label: "Eon Harness", tt: 300 },
  { label: "Eon Harness (L)", tt: 300 },
  { label: "Eon Harness, SGA Edition", tt: 300 },
  { label: "Eon Helmet", tt: 170 },
  { label: "Eon Helmet (L)", tt: 170 },
  { label: "Eon Helmet, SGA Edition", tt: 170 },
  { label: "Eon Shin Guards", tt: 205 },
  { label: "Eon Shin Guards (L)", tt: 205 },
  { label: "Eon Shin Guards, SGA Edition", tt: 205 },
  { label: "Eon Thigh Guards", tt: 220 },
  { label: "Eon Thigh Guards (L)", tt: 220 },
  { label: "Eon Thigh Guards, SGA Edition", tt: 220 },
  { label: "Ethereal Armor Arm Guards", tt: 128 },
  { label: "Ethereal Armor Face Mask", tt: 112 },
  { label: "Ethereal Armor Foot Guards", tt: 72 },
  { label: "Ethereal Armor Gloves", tt: 72 },
  { label: "Ethereal Armor Harness", tt: 176 },
  { label: "Ethereal Armor Shin Guards", tt: 112 },
  { label: "Ethereal Armor Thigh Guards", tt: 128 },
  { label: "Expedition Arm Guards", tt: 23 },
  { label: "Expedition Foot Guards", tt: 21 },
  { label: "Expedition Gloves", tt: 21 },
  { label: "Expedition Harness", tt: 41 },
  { label: "Expedition Helmet", tt: 20 },
  { label: "Expedition Shin Guards", tt: 21 },
  { label: "Expedition Thigh Guards", tt: 24 },
  { label: "Explorer Arm Guards", tt: 9.4 },
  { label: "Explorer Face Guard", tt: 4.7 },
  { label: "Explorer Foot Guards", tt: 4.7 },
  { label: "Explorer Gloves", tt: 4.7 },
  { label: "Explorer Harness", tt: 14.1 },
  { label: "Explorer Shin Guards", tt: 4.7 },
  { label: "Explorer Thigh Guards", tt: 9.4 },
  { label: "Firewall Arm Guards (L)", tt: 18 },
  { label: "Firewall Foot Guards (L)", tt: 14 },
  { label: "Firewall Gloves (L)", tt: 21 },
  { label: "Firewall Harness (L)", tt: 23.5 },
  { label: "Firewall Harness Mk-II", tt: 45.5 },
  { label: "Firewall Helmet (L)", tt: 15 },
  { label: "Firewall Mk-II Arm Guards (L)", tt: 36 },
  { label: "Firewall Mk-II Foot Guards (L)", tt: 30 },
  { label: "Firewall Mk-II Gloves (L)", tt: 32 },
  { label: "Firewall Mk-II Harness (L)", tt: 45.5 },
  { label: "Firewall Mk-II Helmet (L)", tt: 35 },
  { label: "Firewall Mk-III Arm Guards (L)", tt: 78 },
  { label: "Firewall Mk-III Foot Guards (L)", tt: 65 },
  { label: "Firewall Mk-III Gloves (L)", tt: 62 },
  { label: "Firewall Mk-III Harness (L)", tt: 85.5 },
  { label: "Firewall Mk-III Helmet (L)", tt: 70 },
  { label: "Firewall Mk-III Shin Guards (L)", tt: 60 },
  { label: "Firewall Mk-III Thigh Guards (L)", tt: 75 },
  { label: "Firewall Mk-II Shin Guards (L)", tt: 31 },
  { label: "Firewall Mk-II Thigh Guards (L)", tt: 38 },
  { label: "Firewall Shin Guards (L)", tt: 16 },
  { label: "Firewall Thigh Guards (L)", tt: 22 },
  { label: "Foot Guards of the Wormslayer", tt: 88 },
  { label: "Ghost Arm Guards", tt: 45 },
  { label: "Ghost Arm Guards (L)", tt: 45 },
  { label: "Ghost Face Mask", tt: 48 },
  { label: "Ghost Face Mask (L)", tt: 48 },
  { label: "Ghost Foot Guards", tt: 46 },
  { label: "Ghost Foot Guards (L)", tt: 46 },
  { label: "Ghost Gloves", tt: 46 },
  { label: "Ghost Gloves (L)", tt: 46 },
  { label: "Ghost Harness", tt: 74 },
  { label: "Ghost Harness (L)", tt: 74 },
  { label: "Ghost Shin Guards", tt: 44 },
  { label: "Ghost Shin Guards (L)", tt: 44 },
  { label: "Ghost Thigh Guards", tt: 45 },
  { label: "Ghost Thigh Guards (L)", tt: 45 },
  { label: "Ghoul Arm Guards", tt: 62 },
  { label: "Ghoul Face Mask", tt: 60 },
  { label: "Ghoul Foot Guards", tt: 64 },
  { label: "Ghoul Gloves", tt: 64 },
  { label: "Ghoul Harness", tt: 112 },
  { label: "Ghoul Shin Guards", tt: 56 },
  { label: "Ghoul Thigh Guards", tt: 56 },
  { label: "Gloves of the Wormslayer", tt: 153 },
  { label: "Gnome Arm Guards", tt: 4 },
  { label: "Gnome Face Mask", tt: 3.99 },
  { label: "Gnome Foot Guards", tt: 3.8 },
  { label: "Gnome Gloves", tt: 3.8 },
  { label: "Gnome Harness", tt: 4.9 },
  { label: "Gnome Shin Guards", tt: 3.84 },
  { label: "Gnome Thigh Guards", tt: 3.85 },
  { label: "Goblin Arm Guards", tt: 5.9 },
  { label: "Goblin Arm Guards, SGA Edition", tt: 5.9 },
  { label: "Goblin Face Guard", tt: 3.7 },
  { label: "Goblin Face Guard, SGA Edition", tt: 3.7 },
  { label: "Goblin Foot Guards", tt: 3.56 },
  { label: "Goblin Foot Guards, SGA Edition", tt: 3.56 },
  { label: "Goblin Gloves", tt: 3.56 },
  { label: "Goblin Gloves, SGA Edition", tt: 3.56 },
  { label: "Goblin Harness", tt: 8 },
  { label: "Goblin Harness, SGA Edition", tt: 8 },
  { label: "Goblin Shin Guards", tt: 5.87 },
  { label: "Goblin Shin Guards, SGA Edition", tt: 5.87 },
  { label: "Goblin Thigh Guards", tt: 6.1 },
  { label: "Goblin Thigh Guards, SGA Edition", tt: 6.1 },
  { label: "Goldenweave Mask (L)", tt: 42 },
  { label: "Gold Rush 2016 Arm Guards", tt: 105 },
  { label: "Gold Rush 2016 Foot Guards", tt: 75 },
  { label: "Gold Rush 2016 Gloves", tt: 75 },
  { label: "Gold Rush 2016 Harness", tt: 160 },
  { label: "Gold Rush 2016 Helmet", tt: 65 },
  { label: "Gold Rush 2016 Shin Guards", tt: 90 },
  { label: "Gold Rush 2016 Thigh Guards", tt: 105 },
  { label: "Gremlin Arm Guards", tt: 67.2 },
  { label: "Gremlin Arm Guards Mentor Edition", tt: 67.2 },
  { label: "Gremlin Face Guard", tt: 61.3 },
  { label: "Gremlin Foot Guards", tt: 63.2 },
  { label: "Gremlin Foot Guards Mentor Edition", tt: 63.2 },
  { label: "Gremlin Gloves", tt: 63.2 },
  { label: "Gremlin Gloves Mentor Edition", tt: 63.2 },
  { label: "Gremlin Harness", tt: 81.9 },
  { label: "Gremlin Shin Guards", tt: 73.4 },
  { label: "Gremlin Shin Guards Mentor Edition", tt: 73.4 },
  { label: "Gremlin Thigh Guards", tt: 74 },
  { label: "Grunt Arm Guards", tt: 2.1 },
  { label: "Grunt Arm Guards (C)", tt: 2.1 },
  { label: "Grunt Combat Mask", tt: 1.45 },
  { label: "Grunt Combat Mask (C)", tt: 1.45 },
  { label: "Grunt Foot Guards", tt: 1.9 },
  { label: "Grunt Foot Guards (C)", tt: 1.9 },
  { label: "Grunt Gloves", tt: 0.8 },
  { label: "Grunt Gloves (C)", tt: 0.8 },
  { label: "Grunt Harness", tt: 2.9 },
  { label: "Grunt Harness (C)", tt: 2.9 },
  { label: "Grunt Shin Guards", tt: 1.95 },
  { label: "Grunt Shin Guards (C)", tt: 1.95 },
  { label: "Grunt Thigh Guards", tt: 2.1 },
  { label: "Grunt Thigh Guards (C)", tt: 2.1 },
  { label: "Guardian Arm Guards", tt: 6.2 },
  { label: "Guardian Arm Guards Adjusted", tt: 10 },
  { label: "Guardian Face Guard", tt: 3.1 },
  { label: "Guardian Face Guard Adjusted", tt: 5 },
  { label: "Guardian Foot Guards", tt: 3.1 },
  { label: "Guardian Gloves", tt: 3.1 },
  { label: "Guardian Harness", tt: 9.3 },
  { label: "Guardian Harness Adjusted", tt: 15 },
  { label: "Guardian Shin Guards", tt: 3.1 },
  { label: "Guardian Shin Guards Adjusted", tt: 5 },
  { label: "Guardian Thigh Guards", tt: 6.2 },
  { label: "Haris Armor Arm Guards (L)", tt: 5.75 },
  { label: "Haris Armor Harness (L)", tt: 8 },
  { label: "Haris Armor Helmet (L)", tt: 5 },
  { label: "Haris Armor Thigh Guards (L)", tt: 5.75 },
  { label: "Harness of the Wormslayer", tt: 230 },
  { label: "Harrier Assault Arm Guards", tt: 2.2 },
  { label: "Harrier Assault Arm Guards Adjusted", tt: 2.2 },
  { label: "Harrier Assault Foot Guards", tt: 1.1 },
  { label: "Harrier Assault Foot Guards Adjusted", tt: 1.1 },
  { label: "Harrier Assault Gloves", tt: 1.1 },
  { label: "Harrier Assault Gloves Adjusted", tt: 1.1 },
  { label: "Harrier Assault Harness", tt: 3.2 },
  { label: "Harrier Assault Harness Adjusted", tt: 3.2 },
  { label: "Harrier Assault Helmet", tt: 1.1 },
  { label: "Harrier Assault Helmet Adjusted", tt: 1.1 },
  { label: "Harrier Assault Shin Guards", tt: 1.1 },
  { label: "Harrier Assault Shin Guards Adjusted", tt: 1.1 },
  { label: "Harrier Assault Thigh Guards", tt: 2.2 },
  { label: "Harrier Assault Thigh Guards Adjusted", tt: 2.2 },
  { label: "Harrier Scout Arm Guards", tt: 1.1 },
  { label: "Harrier Scout Foot Guards", tt: 0.55 },
  { label: "Harrier Scout Gloves", tt: 0.55 },
  { label: "Harrier Scout Harness", tt: 1.6 },
  { label: "Harrier Scout Helmet", tt: 0.55 },
  { label: "Harrier Scout Shin Guards", tt: 0.55 },
  { label: "Harrier Scout Thigh Guards", tt: 1.1 },
  { label: "Helmet of the Wormslayer", tt: 88 },
  { label: "Heran Armor Arm Guards (L)", tt: 4 },
  { label: "Heran Armor Foot Guards (L)", tt: 2.5 },
  { label: "Heran Armor Gloves (L)", tt: 2.5 },
  { label: "Heran Armor Harness (L)", tt: 5.8 },
  { label: "Heran Armor Helmet (L)", tt: 3.6 },
  { label: "Heran Armor Shin Guards (L)", tt: 3.6 },
  { label: "Heran Armor Thigh Guards (L)", tt: 4 },
  { label: "Hermes Arm Guards (L)", tt: 105 },
  { label: "Hermes Back Strap (L)", tt: 151 },
  { label: "Hermes Foot Guards (L)", tt: 101 },
  { label: "Hermes Gloves (L)", tt: 101 },
  { label: "Hermes Groin Guard (L)", tt: 109 },
  { label: "Hermes Head Piece (L)", tt: 109 },
  { label: "Hermes Helmet (L)", tt: 109 },
  { label: "Hermes Shin Guards (L)", tt: 110 },
  { label: "Hermes Shoulder Guard (L)", tt: 151 },
  { label: "Holy Arm Guards (L)", tt: 66 },
  { label: "Holy Foot Guards (L)", tt: 33 },
  { label: "Holy Gloves (L)", tt: 33 },
  { label: "Holy Harness (L)", tt: 99 },
  { label: "Holy Helmet (L)", tt: 33 },
  { label: "Holy Shin Guards (L)", tt: 33 },
  { label: "Holy Thigh Guards (L)", tt: 66 },
  { label: "Hoplite Armbands (C)", tt: 3 },
  { label: "Hoplite Breastplate (C)", tt: 7 },
  { label: "Hoplite Gloves (C)", tt: 3 },
  { label: "Hoplite Greaves (C)", tt: 3 },
  { label: "Hoplite Helmet (C)", tt: 5 },
  { label: "Hoplite Sandals (C)", tt: 3 },
  { label: "Hoplite Thigh Armor (C)", tt: 3 },
  { label: "Hunter Arm Guards", tt: 22.25 },
  { label: "Hunter Arm Guards Mentor Edition", tt: 22.25 },
  { label: "Hunter Face Guard", tt: 11.12 },
  { label: "Hunter Face Guard Mentor Edition", tt: 11.12 },
  { label: "Hunter Foot Guards", tt: 11.12 },
  { label: "Hunter Foot Guards Mentor Edition", tt: 11.12 },
  { label: "Hunter Gloves", tt: 11.12 },
  { label: "Hunter Gloves Mentor Edition", tt: 11.12 },
  { label: "Hunter Harness", tt: 33.37 },
  { label: "Hunter Harness Mentor Edition", tt: 33.37 },
  { label: "Hunter Shin Guards", tt: 11.12 },
  { label: "Hunter Shin Guards Mentor Edition", tt: 11.12 },
  { label: "Hunter Thigh Guards", tt: 22.25 },
  { label: "Hunter Thigh Guards Mentor Edition", tt: 22.25 },
  { label: "Hydra Arm Guards", tt: 60 },
  { label: "Hydra Arm Guards (L)", tt: 56 },
  { label: "Hydra Foot Guards", tt: 44 },
  { label: "Hydra Foot Guards (L)", tt: 48 },
  { label: "Hydra Gloves", tt: 36 },
  { label: "Hydra Gloves (L)", tt: 40 },
  { label: "Hydra Harness", tt: 96 },
  { label: "Hydra Harness (L)", tt: 96 },
  { label: "Hydra Helmet", tt: 52 },
  { label: "Hydra Helmet (L)", tt: 52 },
  { label: "Hydra Shin Guards", tt: 56 },
  { label: "Hydra Shin Guards (L)", tt: 52 },
  { label: "Hydra Thigh Guards", tt: 56 },
  { label: "Hydra Thigh Guards (L)", tt: 56 },
  { label: "HyperSense Spectacles", tt: 8 },
  { label: "IFN Prototype Arm Guards (L)", tt: 75 },
  { label: "IFN Prototype Arm Guards MKII (L)", tt: 75 },
  { label: "IFN Prototype Foot Guards (L)", tt: 55 },
  { label: "IFN Prototype Foot Guards MKII (L)", tt: 55 },
  { label: "IFN Prototype Gloves (L)", tt: 45 },
  { label: "IFN Prototype Gloves MKII (L)", tt: 45 },
  { label: "IFN Prototype Harness (L)", tt: 120 },
  { label: "IFN Prototype Harness MKII (L)", tt: 120 },
  { label: "IFN Prototype Helmet (L)", tt: 65 },
  { label: "IFN Prototype Helmet MKII (L)", tt: 65 },
  { label: "IFN Prototype Shin Guards (L)", tt: 70 },
  { label: "IFN Prototype Shin Guards MKII (L)", tt: 70 },
  { label: "IFN Prototype Thigh Guards (L)", tt: 70 },
  { label: "IFN Prototype Thigh Guards MKII (L)", tt: 70 },
  { label: "Imperial HAZEN Arm Guards", tt: 132 },
  { label: "Imperial HAZEN Foot Guards", tt: 83 },
  { label: "Imperial HAZEN Gloves", tt: 83 },
  { label: "Imperial HAZEN Harness", tt: 180 },
  { label: "Imperial HAZEN Helm", tt: 98 },
  { label: "Imperial HAZEN Shin Guards", tt: 110 },
  { label: "Imperial HAZEN Thigh Guards", tt: 145 },
  { label: "Imperium Arm Guards (L)", tt: 64 },
  { label: "Imperium Boots (L)", tt: 64 },
  { label: "Imperium Bracers (L)", tt: 64 },
  { label: "Imperium Gloves (L)", tt: 64 },
  { label: "Imperium Greaves (L)", tt: 64 },
  { label: "Imperium Mask (L)", tt: 64 },
  { label: "Imperium Protector (L)", tt: 64 },
  { label: "Imperium Vet Chest Guard (L)", tt: 85 },
  { label: "Infiltrator Arm Guards (L)", tt: 165 },
  { label: "Infiltrator Arm Guards (L) Reworked", tt: 165 },
  { label: "Infiltrator Foot Guards (L)", tt: 165 },
  { label: "Infiltrator Foot Guards (L) Reworked", tt: 165 },
  { label: "Infiltrator Gloves (L)", tt: 165 },
  { label: "Infiltrator Gloves (L) Reworked", tt: 165 },
  { label: "Infiltrator Harness (L)", tt: 219 },
  { label: "Infiltrator Harness (L) Reworked", tt: 219 },
  { label: "Infiltrator Helmet (L)", tt: 111.5 },
  { label: "Infiltrator Helmet (L) Reworked", tt: 111.5 },
  { label: "Infiltrator Shin Guards (L)", tt: 167 },
  { label: "Infiltrator Shin Guards (L) Reworked", tt: 167 },
  { label: "Infiltrator Thigh Guards (L)", tt: 171.5 },
  { label: "Infiltrator Thigh Guards (L) Reworked", tt: 171.5 },
  { label: "Jaguar Arm Guards", tt: 73 },
  { label: "Jaguar Arm Guards (L)", tt: 73 },
  { label: "Jaguar Arm Guards, SGA Edition", tt: 73 },
  { label: "Jaguar Arm Guards Adjusted", tt: 73 },
  { label: "Jaguar Foot Guards", tt: 66 },
  { label: "Jaguar Foot Guards (L)", tt: 66 },
  { label: "Jaguar Foot Guards, SGA Edition", tt: 66 },
  { label: "Jaguar Foot Guards Adjusted", tt: 66 },
  { label: "Jaguar Gloves", tt: 66 },
  { label: "Jaguar Gloves (L)", tt: 66 },
  { label: "Jaguar Gloves, SGA Edition", tt: 66 },
  { label: "Jaguar Gloves Adjusted", tt: 66 },
  { label: "Jaguar Harness", tt: 167.4 },
  { label: "Jaguar Harness (L)", tt: 167.4 },
  { label: "Jaguar Harness, SGA Edition", tt: 167.4 },
  { label: "Jaguar Harness Adjusted", tt: 167.4 },
  { label: "Jaguar Helmet", tt: 71.7 },
  { label: "Jaguar Helmet (L)", tt: 71.7 },
  { label: "Jaguar Helmet, SGA Edition", tt: 71.7 },
  { label: "Jaguar Helmet Adjusted", tt: 71.7 },
  { label: "Jaguar Shin Guards", tt: 78.9 },
  { label: "Jaguar Shin Guards (L)", tt: 78.9 },
  { label: "Jaguar Shin Guards, SGA Edition", tt: 78.9 },
  { label: "Jaguar Shin Guards Adjusted", tt: 78.9 },
  { label: "Jaguar Thigh Guards", tt: 83.4 },
  { label: "Jaguar Thigh Guards (L)", tt: 83.4 },
  { label: "Jaguar Thigh Guards, SGA Edition", tt: 83.4 },
  { label: "Jaguar Thigh Guards Adjusted", tt: 83.4 },
  { label: "Jarhead Arm Guards (C)", tt: 55 },
  { label: "Jarhead Arm Guards (L)", tt: 55 },
  { label: "Jarhead Combat Mask (C)", tt: 51 },
  { label: "Jarhead Combat Mask (L)", tt: 51 },
  { label: "Jarhead Foot Guards (C)", tt: 46 },
  { label: "Jarhead Foot Guards (L)", tt: 53 },
  { label: "Jarhead Gloves (C)", tt: 56 },
  { label: "Jarhead Gloves (L)", tt: 56 },
  { label: "Jarhead Harness (C)", tt: 74 },
  { label: "Jarhead Harness (L)", tt: 74 },
  { label: "Jarhead Shin Guards (C)", tt: 48 },
  { label: "Jarhead Shin Guards (L)", tt: 48 },
  { label: "Jarhead Thigh Guards (C)", tt: 49 },
  { label: "Jarhead Thigh Guards (L)", tt: 49 },
  { label: "Knight Arm Guards", tt: 27 },
  { label: "Knight Face Guard", tt: 13.5 },
  { label: "Knight Foot Guards", tt: 13.5 },
  { label: "Knight Gloves", tt: 13.5 },
  { label: "Knight Harness", tt: 40.5 },
  { label: "Knight Shin Guards", tt: 13.5 },
  { label: "Knight Thigh Guards", tt: 27 },
  { label: "Kobold Arm Guards", tt: 18.3 },
  { label: "Kobold Arm Guards, SGA Edition", tt: 18.3 },
  { label: "Kobold Face Guard", tt: 17.5 },
  { label: "Kobold Face Guard, SGA Edition", tt: 17.5 },
  { label: "Kobold Foot Guards", tt: 16.5 },
  { label: "Kobold Foot Guards, SGA Edition", tt: 16.5 },
  { label: "Kobold Gloves", tt: 16.5 },
  { label: "Kobold Gloves, SGA Edition", tt: 16.5 },
  { label: "Kobold Harness", tt: 22.6 },
  { label: "Kobold Harness, SGA Edition", tt: 22.6 },
  { label: "Kobold Shin Guards", tt: 21.2 },
  { label: "Kobold Shin Guards, SGA Edition", tt: 21.2 },
  { label: "Kobold Thigh Guards", tt: 20.2 },
  { label: "Kobold Thigh Guards, SGA Edition", tt: 20.2 },
  { label: "Koroma Arm Guards", tt: 5.6 },
  { label: "Koroma Foot Guards", tt: 4.8 },
  { label: "Koroma Gloves", tt: 4 },
  { label: "Koroma Harness", tt: 9.6 },
  { label: "Koroma Helmet", tt: 5.2 },
  { label: "Koroma Shin Guards", tt: 5.2 },
  { label: "Koroma Thigh Guards", tt: 5.6 },
  { label: "Liakon Arm Guards", tt: 42 },
  { label: "Liakon Foot Guards", tt: 20 },
  { label: "Liakon Gloves", tt: 48 },
  { label: "Liakon Harness", tt: 48 },
  { label: "Liakon Helmet", tt: 26 },
  { label: "Liakon Shin Guards", tt: 28 },
  { label: "Liakon Thigh Guards", tt: 42 },
  { label: "Lich Arm Guards (L)", tt: 101 },
  { label: "Lich Foot Guards (L)", tt: 97 },
  { label: "Lich Gloves (L)", tt: 97 },
  { label: "Lich Harness (L)", tt: 147 },
  { label: "Lich Helmet (L)", tt: 105 },
  { label: "Lich Shin Guards (L)", tt: 106 },
  { label: "Lich Thigh Guards (L)", tt: 105 },
  { label: "Lion Arm Guards", tt: 110 },
  { label: "Lion Foot Guards", tt: 91 },
  { label: "Lion Gloves", tt: 91 },
  { label: "Lion Harness", tt: 145 },
  { label: "Lion Helmet", tt: 110 },
  { label: "Lion Shin Guards", tt: 99 },
  { label: "Lion Thigh Guards", tt: 120 },
  { label: "Luna Arm Guards (L)", tt: 85 },
  { label: "Luna Foot Guards (L)", tt: 85 },
  { label: "Luna Gloves (L)", tt: 85 },
  { label: "Luna Harness (L)", tt: 113.5 },
  { label: "Luna Helmet (L)", tt: 57 },
  { label: "Luna Shin Guards (L)", tt: 88.5 },
  { label: "Luna Thigh Guards (L)", tt: 89 },
  { label: "Lupus Arm Guards", tt: 27 },
  { label: "Lupus Arm Guards (L)", tt: 25 },
  { label: "Lupus Foot Guards", tt: 19.8 },
  { label: "Lupus Foot Guards (L)", tt: 22 },
  { label: "Lupus Gloves", tt: 16.4 },
  { label: "Lupus Gloves (L)", tt: 19 },
  { label: "Lupus Harness", tt: 43.2 },
  { label: "Lupus Harness (L)", tt: 43 },
  { label: "Lupus Helmet", tt: 23.4 },
  { label: "Lupus Helmet (L)", tt: 23 },
  { label: "Lupus Shin Guards", tt: 25.2 },
  { label: "Lupus Shin Guards (L)", tt: 23 },
  { label: "Lupus Thigh Guards", tt: 25.2 },
  { label: "Lupus Thigh Guards (L)", tt: 25 },
  { label: "Mah'ketta Arm Guards", tt: 28 },
  { label: "Mah'ketta Foot Guards", tt: 24 },
  { label: "Mah'ketta Gloves", tt: 20 },
  { label: "Mah'ketta Harness", tt: 48 },
  { label: "Mah'ketta Helmet", tt: 26 },
  { label: "Mah'ketta Shin Guards", tt: 26 },
  { label: "Mah'ketta Thigh Guards", tt: 28 },
  { label: "Malware Arm Guards (L)", tt: 150 },
  { label: "Malware Helmet (L)", tt: 75 },
  { label: "Malware Shin Guards (L)", tt: 75 },
  { label: "Martial Arm Guards (L)", tt: 66 },
  { label: "Martial Arm Guards, SGA Edition", tt: 66 },
  { label: "Martial Foot Guards (L)", tt: 66 },
  { label: "Martial Foot Guards, SGA Edition", tt: 66 },
  { label: "Martial Gloves (L)", tt: 66 },
  { label: "Martial Gloves, SGA Edition", tt: 66 },
  { label: "Martial Harness (L)", tt: 110 },
  { label: "Martial Harness, SGA Edition", tt: 110 },
  { label: "Martial Helmet (L)", tt: 59.2 },
  { label: "Martial Helmet, SGA Edition", tt: 59.2 },
  { label: "Martial Shin Guards (L)", tt: 55 },
  { label: "Martial Shin Guards, SGA Edition", tt: 55 },
  { label: "Martial Thigh Guards (L)", tt: 64.5 },
  { label: "Martial Thigh Guards, SGA Edition", tt: 64.5 },
  { label: "Mawlood Armor Arm Guards (L)", tt: 2.25 },
  { label: "Mawlood Armor Foot Guards (L)", tt: 1.25 },
  { label: "Mawlood Armor Gloves (L)", tt: 1.25 },
  { label: "Mawlood Armor Harness (L)", tt: 3 },
  { label: "Mawlood Armor Helmet (L)", tt: 3.6 },
  { label: "Mawlood Armor Shin Guards (L)", tt: 2 },
  { label: "Mawlood Armor Thigh Guards (L)", tt: 2.25 },
  { label: "Mawlood Starter Armor Harness (L)", tt: 4.4 },
  { label: "Mayhem Arm Guards", tt: 100 },
  { label: "Mayhem Arm Guards (L)", tt: 100 },
  { label: "Mayhem Foot Guards", tt: 60 },
  { label: "Mayhem Foot Guards (L)", tt: 60 },
  { label: "Mayhem Gloves", tt: 60 },
  { label: "Mayhem Gloves (L)", tt: 60 },
  { label: "Mayhem Harness", tt: 180 },
  { label: "Mayhem Harness (L)", tt: 180 },
  { label: "Mayhem Helmet", tt: 100 },
  { label: "Mayhem Helmet (L)", tt: 100 },
  { label: "Mayhem Shin Guards", tt: 60 },
  { label: "Mayhem Shin Guards (L)", tt: 60 },
  { label: "Mayhem Thigh Guards", tt: 100 },
  { label: "Mayhem Thigh Guards (L)", tt: 100 },
  { label: "Merry Mayhem 08 Harness", tt: 275 },
  { label: "Merry Mayhem 09 Helmet", tt: 146 },
  { label: "Merry Mayhem 10 Arm Guards", tt: 195 },
  { label: "Merry Mayhem 11 Thigh Guards", tt: 210 },
  { label: "Merry Mayhem 12 Shin Guards", tt: 146 },
  { label: "Merry Mayhem 13 Foot Guards", tt: 160 },
  { label: "Merry Mayhem 14 Gloves", tt: 146 },
  { label: "MMOWC X1 Arm Guards", tt: 80 },
  { label: "MMOWC X1 Foot Guards", tt: 45 },
  { label: "MMOWC X1 Gloves", tt: 45 },
  { label: "MMOWC X1 Harness", tt: 110 },
  { label: "MMOWC X1 Helmet", tt: 70 },
  { label: "MMOWC X1 Shin Guards", tt: 70 },
  { label: "MMOWC X1 Thigh Guards", tt: 80 },
  { label: "Moonshine Arm Guards (L)", tt: 115 },
  { label: "Moonshine Foot Guards (L)", tt: 96 },
  { label: "Moonshine Gloves (L)", tt: 96 },
  { label: "Moonshine Harness (L)", tt: 189 },
  { label: "Moonshine Helmet (L)", tt: 90 },
  { label: "Moonshine Shin Guards (L)", tt: 102 },
  { label: "Moonshine Thigh Guards (L)", tt: 115 },
  { label: "Musca Arm Guards (L)", tt: 5.6 },
  { label: "Musca Arm Guards Adjusted", tt: 4.2 },
  { label: "Musca Foot Guards (L)", tt: 4.8 },
  { label: "Musca Foot Guards Adjusted", tt: 3.8 },
  { label: "Musca Gloves (L)", tt: 4 },
  { label: "Musca Gloves Adjusted", tt: 3.8 },
  { label: "Musca Harness (L)", tt: 9.6 },
  { label: "Musca Harness Adjusted", tt: 5.8 },
  { label: "Musca Helmet (L)", tt: 5.2 },
  { label: "Musca Helmet Adjusted", tt: 2.9 },
  { label: "Musca Shin Guards (L)", tt: 5.2 },
  { label: "Musca Shin Guards Adjusted", tt: 3.9 },
  { label: "Musca Thigh Guards (L)", tt: 5.6 },
  { label: "Musca Thigh Guards Adjusted", tt: 4.2 },
  { label: "Necromancer Arm Guards (L)", tt: 170 },
  { label: "Necromancer Foot Guards (L)", tt: 156 },
  { label: "Necromancer Gloves (L)", tt: 156 },
  { label: "Necromancer Harness (L)", tt: 193 },
  { label: "Necromancer Helmet (L)", tt: 170 },
  { label: "Necromancer Shin Guards (L)", tt: 155 },
  { label: "Necromancer Thigh Guards (L)", tt: 164 },
  { label: "Nemesis Arm Guards", tt: 42.75 },
  { label: "Nemesis Arm Guards Adjusted", tt: 42.75 },
  { label: "Nemesis Foot Guards", tt: 21.37 },
  { label: "Nemesis Foot Guards Adjusted", tt: 21.37 },
  { label: "Nemesis Gloves", tt: 21.37 },
  { label: "Nemesis Gloves Adjusted", tt: 21.37 },
  { label: "Nemesis Harness", tt: 64.12 },
  { label: "Nemesis Harness Adjusted", tt: 64.12 },
  { label: "Nemesis Helmet", tt: 21.37 },
  { label: "Nemesis Helmet Adjusted", tt: 21.37 },
  { label: "Nemesis Shin Guards", tt: 21.37 },
  { label: "Nemesis Shin Guards Adjusted", tt: 21.37 },
  { label: "Nemesis Thigh Guards", tt: 42.75 },
  { label: "Nemesis Thigh Guards Adjusted", tt: 42.75 },
  { label: "Optimus Prime Helmet", tt: 20 },
  { label: "Orca Arm Guards (L)", tt: 47.5 },
  { label: "Orca Foot Guards (L)", tt: 47.5 },
  { label: "Orca Gloves (L)", tt: 47.5 },
  { label: "Orca Harness (L)", tt: 60 },
  { label: "Orca Helmet (L)", tt: 35.5 },
  { label: "Orca Shin Guards (L)", tt: 45 },
  { label: "Orca Thigh Guards (L)", tt: 46 },
  { label: "Ozpyn Beetle Arm Guards (L)", tt: 44 },
  { label: "Ozpyn Beetle Chest Guard (L)", tt: 64 },
  { label: "Ozpyn Beetle Foot Guards (L)", tt: 44 },
  { label: "Ozpyn Beetle Hand Guards (L)", tt: 40 },
  { label: "Ozpyn Beetle Head Guard (L)", tt: 64 },
  { label: "Ozpyn Beetle Shin Guards (L)", tt: 56 },
  { label: "Ozpyn Beetle Thigh Guards (L)", tt: 52 },
  { label: "Ozpyn Force Arm Guards (L)", tt: 90 },
  { label: "Ozpyn Force Foot Guards (L)", tt: 85 },
  { label: "Ozpyn Force Hand Guards (L)", tt: 90 },
  { label: "Ozpyn Force Harness (L)", tt: 100 },
  { label: "Ozpyn Force Helmet (L)", tt: 100 },
  { label: "Ozpyn Force Shin Guards (L)", tt: 95 },
  { label: "Ozpyn Force Thigh Guards (L)", tt: 90 },
  { label: "Paladin Arm Guards", tt: 41 },
  { label: "Paladin Face Guard", tt: 25 },
  { label: "Paladin Foot Guards", tt: 25.5 },
  { label: "Paladin Foot Guards TEN Edition", tt: 28.81 },
  { label: "Paladin Gloves", tt: 25.5 },
  { label: "Paladin Harness", tt: 66.5 },
  { label: "Paladin Harness TEN Edition", tt: 75.14 },
  { label: "Paladin Shin Guards", tt: 15.5 },
  { label: "Paladin Thigh Guards", tt: 41 },
  { label: "Paradox Arm Guards", tt: 120 },
  { label: "Paradox Foot Guards", tt: 80 },
  { label: "Paradox Gloves", tt: 80 },
  { label: "Paradox Harness", tt: 160 },
  { label: "Paradox Helmet", tt: 100 },
  { label: "Paradox Shin Guards", tt: 130 },
  { label: "Paradox Thigh Guards", tt: 110 },
  { label: "Pathfinder Arm Guards", tt: 2 },
  { label: "Pathfinder Face Guard", tt: 2 },
  { label: "Pathfinder Foot Guards", tt: 2 },
  { label: "Pathfinder Gloves", tt: 2 },
  { label: "Pathfinder Harness", tt: 2 },
  { label: "Pathfinder Shin Guards", tt: 2 },
  { label: "Pathfinder Thigh Guards", tt: 2 },
  { label: "Pegasus Arm Guards (L)", tt: 84 },
  { label: "Pegasus Foot Guards", tt: 66 },
  { label: "Pegasus Foot Guards (L)", tt: 72 },
  { label: "Pegasus Gloves", tt: 54 },
  { label: "Pegasus Gloves (L)", tt: 60 },
  { label: "Pegasus Harness", tt: 144 },
  { label: "Pegasus Harness (L)", tt: 144 },
  { label: "Pegasus Helmet", tt: 78 },
  { label: "Pegasus Helmet (L)", tt: 78 },
  { label: "Pegasus Shin Guards", tt: 84 },
  { label: "Pegasus Shin Guards (L)", tt: 78 },
  { label: "Pegasus Thigh Guards", tt: 84 },
  { label: "Pegasus Thigh Guards (L)", tt: 84 },
  { label: "Perseus Arm Guards (L)", tt: 140 },
  { label: "Perseus Foot Guards", tt: 110 },
  { label: "Perseus Foot Guards (L)", tt: 120 },
  { label: "Perseus Gloves", tt: 90 },
  { label: "Perseus Gloves (L)", tt: 100 },
  { label: "Perseus Harness (L)", tt: 240 },
  { label: "Perseus Helmet", tt: 130 },
  { label: "Perseus Helmet (L)", tt: 130 },
  { label: "Perseus Shin Guards", tt: 140 },
  { label: "Perseus Shin Guards (L)", tt: 130 },
  { label: "Perseus Thigh Guards", tt: 140 },
  { label: "Perseus Thigh Guards (L)", tt: 140 },
  { label: "Phantom Arm Guards", tt: 55 },
  { label: "Phantom Face Mask", tt: 55 },
  { label: "Phantom Foot Guards", tt: 56 },
  { label: "Phantom Gloves", tt: 56 },
  { label: "Phantom Harness", tt: 86 },
  { label: "Phantom Shin Guards", tt: 51 },
  { label: "Phantom Thigh Guards", tt: 52 },
  { label: "Pioneer Arm Guards", tt: 4 },
  { label: "Pioneer Arm Guards (L)", tt: 12 },
  { label: "Pioneer Face Guard", tt: 2 },
  { label: "Pioneer Face Guard (L)", tt: 6 },
  { label: "Pioneer Foot Guards", tt: 2 },
  { label: "Pioneer Foot Guards (L)", tt: 6 },
  { label: "Pioneer Gloves", tt: 2 },
  { label: "Pioneer Gloves (L)", tt: 6 },
  { label: "Pioneer Harness", tt: 6 },
  { label: "Pioneer Harness (L)", tt: 18 },
  { label: "Pioneer Shin Guards", tt: 2 },
  { label: "Pioneer Shin Guards (L)", tt: 6 },
  { label: "Pioneer Thigh Guards", tt: 4 },
  { label: "Pioneer Thigh Guards (L)", tt: 12 },
  { label: "Pixie Arm Guards", tt: 2.1 },
  { label: "Pixie Arm Guards, SGA Edition", tt: 2.1 },
  { label: "Pixie Arm Guards Adjusted", tt: 4.2 },
  { label: "Pixie Face Guard", tt: 1.45 },
  { label: "Pixie Face Guard, SGA Edition", tt: 1.45 },
  { label: "Pixie Foot Guards", tt: 1.9 },
  { label: "Pixie Foot Guards, SGA Edition", tt: 1.9 },
  { label: "Pixie Foot Guards Adjusted", tt: 3.8 },
  { label: "Pixie Gloves", tt: 1.9 },
  { label: "Pixie Gloves, SGA Edition", tt: 1.9 },
  { label: "Pixie Gloves Adjusted", tt: 3.8 },
  { label: "Pixie Harness", tt: 2.9 },
  { label: "Pixie Harness, SGA Edition", tt: 2.9 },
  { label: "Pixie Harness Adjusted", tt: 5.8 },
  { label: "Pixie Helmet Adjusted", tt: 2.9 },
  { label: "Pixie Shin Guards", tt: 1.95 },
  { label: "Pixie Shin Guards, SGA Edition", tt: 1.95 },
  { label: "Pixie Shin Guards Adjusted", tt: 3.9 },
  { label: "Pixie Thigh Guards", tt: 2.1 },
  { label: "Pixie Thigh Guards, SGA Edition", tt: 2.1 },
  { label: "Pixie Thigh Guards Adjusted", tt: 4.2 },
  { label: "Polaris Arm Guards (L)", tt: 139 },
  { label: "Polaris Foot Guards (L)", tt: 139.5 },
  { label: "Polaris Gloves (L)", tt: 139.5 },
  { label: "Polaris Harness (L)", tt: 185 },
  { label: "Polaris Helmet (L)", tt: 94.5 },
  { label: "Polaris Shin Guards (L)", tt: 141 },
  { label: "Polaris Thigh Guards (L)", tt: 144.5 },
  { label: "Predator Arm Guards (L)", tt: 27 },
  { label: "Predator Foot Guards (L)", tt: 27 },
  { label: "Predator Gloves (L)", tt: 27 },
  { label: "Predator Harness (L)", tt: 40 },
  { label: "Predator Helmet (L)", tt: 28.5 },
  { label: "Predator Shin Guards (L)", tt: 32 },
  { label: "Predator Thigh Guards (L)", tt: 35 },
  { label: "Protector of the Empire Arm Guards", tt: 202.2 },
  { label: "Protector of the Empire Foot Guards", tt: 190 },
  { label: "Protector of the Empire Gloves", tt: 190 },
  { label: "Protector of the Empire Harness", tt: 259 },
  { label: "Protector of the Empire Helmet", tt: 119.4 },
  { label: "Protector of the Empire Shin Guards", tt: 193 },
  { label: "Protector of the Empire Thigh Guards", tt: 206 },
  { label: "Rascal Arm Guards", tt: 8.9 },
  { label: "Rascal Arm Guards (L)", tt: 8.9 },
  { label: "Rascal Face Guard", tt: 7.8 },
  { label: "Rascal Face Guard (L)", tt: 7.8 },
  { label: "Rascal Foot Guards", tt: 7.7 },
  { label: "Rascal Foot Guards (L)", tt: 7.7 },
  { label: "Rascal Gloves", tt: 7.7 },
  { label: "Rascal Gloves (L)", tt: 7.7 },
  { label: "Rascal Harness", tt: 11.2 },
  { label: "Rascal Harness (L)", tt: 11.2 },
  { label: "Rascal Shin Guards", tt: 8.7 },
  { label: "Rascal Shin Guards (L)", tt: 8.7 },
  { label: "Rascal Thigh Guards", tt: 8.65 },
  { label: "Rascal Thigh Guards (L)", tt: 8.65 },
  { label: "Raven Arm Guards", tt: 21 },
  { label: "Raven Foot Guards", tt: 19 },
  { label: "Raven Gloves", tt: 19 },
  { label: "Raven Harness", tt: 29 },
  { label: "Raven Helmet", tt: 19.5 },
  { label: "Raven Shin Guards", tt: 19.5 },
  { label: "Raven Thigh Guards", tt: 21 },
  { label: "Reaper Shin Guards (L)", tt: 185 },
  { label: "Renegade Arm Guards", tt: 10.5 },
  { label: "Renegade Arm Guards (L)", tt: 10.5 },
  { label: "Renegade Face Guard", tt: 7 },
  { label: "Renegade Face Guard (L)", tt: 7 },
  { label: "Renegade Foot Guards", tt: 7 },
  { label: "Renegade Foot Guards (L)", tt: 7 },
  { label: "Renegade Gloves", tt: 7 },
  { label: "Renegade Gloves (L)", tt: 7 },
  { label: "Renegade Harness", tt: 16 },
  { label: "Renegade Harness (L)", tt: 16 },
  { label: "Renegade Shin Guards", tt: 7.1 },
  { label: "Renegade Shin Guards (L)", tt: 7.1 },
  { label: "Renegade Thigh Guards", tt: 11 },
  { label: "Renegade Thigh Guards (L)", tt: 11 },
  { label: "Rifi Armor Arm Guards (L)", tt: 3.2 },
  { label: "Rifi Armor Arm Guards ME", tt: 4.2 },
  { label: "Rifi Armor Foot Guards (L)", tt: 1.8 },
  { label: "Rifi Armor Foot Guards ME", tt: 3.8 },
  { label: "Rifi Armor Gloves (L)", tt: 1.8 },
  { label: "Rifi Armor Gloves ME", tt: 3.8 },
  { label: "Rifi Armor Harness (L)", tt: 4.4 },
  { label: "Rifi Armor Harness ME", tt: 5.8 },
  { label: "Rifi Armor Helmet (L)", tt: 2.8 },
  { label: "Rifi Armor Helmet ME", tt: 2.9 },
  { label: "Rifi Armor Shin Guards (L)", tt: 2.8 },
  { label: "Rifi Armor Shin Guards ME", tt: 3.9 },
  { label: "Rifi Armor Thigh Guards (L)", tt: 3.2 },
  { label: "Rifi Armor Thigh Guards ME", tt: 4.2 },
  { label: "Rutuba Arm Guards (L)", tt: 151.2 },
  { label: "Rutuba Back Strap (L)", tt: 217.5 },
  { label: "Rutuba Foot Guards (L)", tt: 145.5 },
  { label: "Rutuba Gloves (L)", tt: 145.5 },
  { label: "Rutuba Groin Guard (L)", tt: 157 },
  { label: "Rutuba Head Piece (L)", tt: 156.5 },
  { label: "Rutuba Helmet (L)", tt: 156.5 },
  { label: "Rutuba Shin Guards (L)", tt: 158.5 },
  { label: "Rutuba Shoulder Guard (L)", tt: 217.5 },
  { label: "RX OpTac x1 Arm Guards", tt: 59.2 },
  { label: "RX OpTac x1 Foot Guards", tt: 33.3 },
  { label: "RX OpTac x1 Gloves", tt: 33.3 },
  { label: "RX OpTac x1 Harness", tt: 81.4 },
  { label: "RX OpTac x1 Helmet", tt: 51.8 },
  { label: "RX OpTac x1 Shin Guards", tt: 51.8 },
  { label: "RX OpTac x1 Thigh Guards", tt: 59.2 },
  { label: "RX OpTac x2 Arm Guards", tt: 59.2 },
  { label: "RX OpTac x2 Foot Guards", tt: 33.3 },
  { label: "RX OpTac x2 Gloves", tt: 33.3 },
  { label: "RX OpTac x2 Harness", tt: 81.4 },
  { label: "RX OpTac x2 Helmet", tt: 51.8 },
  { label: "RX OpTac x2 Shin Guards", tt: 51.8 },
  { label: "RX OpTac x2 Thigh Guards", tt: 59.2 },
  { label: "Sada Armor Arm Guards (L)", tt: 5 },
  { label: "Sada Armor Gloves (L)", tt: 3 },
  { label: "Sada Armor Harness (L)", tt: 7 },
  { label: "Sada Armor Helmet (L)", tt: 4.5 },
  { label: "Sada Armor Shin Guards (L)", tt: 4.5 },
  { label: "Sada Armor Thigh Guards (L)", tt: 5 },
  { label: "Salamander Arm Guards", tt: 88 },
  { label: "Salamander Arm Guards, SGA Edition", tt: 88 },
  { label: "Salamander Foot Guards", tt: 55 },
  { label: "Salamander Foot Guards, SGA Edition", tt: 55 },
  { label: "Salamander Gloves", tt: 55 },
  { label: "Salamander Gloves, SGA Edition", tt: 55 },
  { label: "Salamander Harness", tt: 120 },
  { label: "Salamander Harness, SGA Edition", tt: 120 },
  { label: "Salamander Helmet", tt: 65 },
  { label: "Salamander Helmet, SGA Edition", tt: 65 },
  { label: "Salamander Shin Guards", tt: 90 },
  { label: "Salamander Shin Guards, SGA Edition", tt: 90 },
  { label: "Salamander Thigh Guards", tt: 80 },
  { label: "Salamander Thigh Guards, SGA Edition", tt: 80 },
  { label: "Samurai Arm Guards", tt: 17 },
  { label: "Samurai Arm Guards Adjusted", tt: 24 },
  { label: "Samurai Face Guard", tt: 8.5 },
  { label: "Samurai Foot Guards", tt: 8.5 },
  { label: "Samurai Foot Guards Adjusted", tt: 12 },
  { label: "Samurai Gloves", tt: 8.5 },
  { label: "Samurai Gloves Adjusted", tt: 12 },
  { label: "Samurai Harness", tt: 25.5 },
  { label: "Samurai Harness Adjusted", tt: 36 },
  { label: "Samurai Shin Guards", tt: 8.5 },
  { label: "Samurai Thigh Guard Adjusted", tt: 24 },
  { label: "Samurai Thigh Guards", tt: 17 },
  { label: "Sand Stormer Arm Guards", tt: 200 },
  { label: "Sand Stormer Foot Guards", tt: 190 },
  { label: "Sand Stormer Gloves", tt: 190 },
  { label: "Sand Stormer Harness", tt: 260 },
  { label: "Sand Stormer Helmet", tt: 120 },
  { label: "Sand Stormer Shin Guards", tt: 190 },
  { label: "Sand Stormer Thigh Guards", tt: 200 },
  { label: "Scout Arm Guards", tt: 5.6 },
  { label: "Scout Boots", tt: 4.8 },
  { label: "Scout Gloves", tt: 4 },
  { label: "Scout Harness", tt: 9.6 },
  { label: "Scout Helmet", tt: 5.2 },
  { label: "Scout Shin Guards", tt: 5.2 },
  { label: "Scout Thigh Guards", tt: 5.6 },
  { label: "Sema Arm Guards (L)", tt: 72.5 },
  { label: "Sema Foot Guards (L)", tt: 72.5 },
  { label: "Sema Gloves (L)", tt: 72.5 },
  { label: "Sema Harness (L)", tt: 95.5 },
  { label: "Sema Helmet (L)", tt: 48.5 },
  { label: "Sema Shin Guards (L)", tt: 74 },
  { label: "Sema Thigh Guards (L)", tt: 71.3 },
  { label: "Sentinel Arm Guards", tt: 235 },
  { label: "Sentinel Arm Guards (L)", tt: 235 },
  { label: "Sentinel Arm Guards, SGA Edition", tt: 225 },
  { label: "Sentinel Foot Guard", tt: 160 },
  { label: "Sentinel Foot Guards (L)", tt: 160 },
  { label: "Sentinel Foot Guards, SGA Edition", tt: 160 },
  { label: "Sentinel Gloves", tt: 160 },
  { label: "Sentinel Gloves (L)", tt: 160 },
  { label: "Sentinel Gloves, SGA Edition", tt: 160 },
  { label: "Sentinel Harness", tt: 340 },
  { label: "Sentinel Harness (L)", tt: 340 },
  { label: "Sentinel Harness, SGA Edition", tt: 340 },
  { label: "Sentinel Helmet", tt: 180 },
  { label: "Sentinel Helmet (L)", tt: 180 },
  { label: "Sentinel Helmet, SGA Edition", tt: 180 },
  { label: "Sentinel Shin Guards", tt: 215 },
  { label: "Sentinel Shin Guards (L)", tt: 215 },
  { label: "Sentinel Shin Guards, SGA Edition", tt: 215 },
  { label: "Sentinel Thigh Guards", tt: 230 },
  { label: "Sentinel Thigh Guards (L)", tt: 230 },
  { label: "Sentinel Thigh Guards, SGA Edition", tt: 230 },
  { label: "Serum Arm Guards (L)", tt: 91 },
  { label: "Serum Foot Guards (L)", tt: 91 },
  { label: "Serum Gloves (L)", tt: 91 },
  { label: "Serum Harness (L)", tt: 120 },
  { label: "Serum Helmet (L)", tt: 65.2 },
  { label: "Serum Shin Guards (L)", tt: 92.5 },
  { label: "Serum Thigh Guards (L)", tt: 96 },
  { label: "Settler Adjusted Harness", tt: 10.5 },
  { label: "Settler Adjusted Thigh guards", tt: 7 },
  { label: "Settler Arm Guards", tt: 3.7 },
  { label: "Settler Face Guard", tt: 1.85 },
  { label: "Settler Foot Guards", tt: 1.85 },
  { label: "Settler Gloves", tt: 1.85 },
  { label: "Settler Harness", tt: 5.55 },
  { label: "Settler Shin Guards", tt: 1.85 },
  { label: "Settler Thigh Guards", tt: 3.7 },
  { label: "Shadow Arm Guards", tt: 102 },
  { label: "Shadow Arm Guards (L)", tt: 102 },
  { label: "Shadow Arm Guards, SGA Edition", tt: 102 },
  { label: "Shadow Foot Guards", tt: 51 },
  { label: "Shadow Foot Guards (L)", tt: 51 },
  { label: "Shadow Foot Guards, SGA Edition", tt: 51 },
  { label: "Shadow Gloves", tt: 51 },
  { label: "Shadow Gloves (L)", tt: 51 },
  { label: "Shadow Gloves, SGA Edition", tt: 51 },
  { label: "Shadow Harness", tt: 153 },
  { label: "Shadow Harness (L)", tt: 153 },
  { label: "Shadow Harness, SGA Edition", tt: 153 },
  { label: "Shadow Helmet", tt: 51 },
  { label: "Shadow Helmet (L)", tt: 51 },
  { label: "Shadow Helmet, SGA Edition", tt: 51 },
  { label: "Shadow Modified Arm guards", tt: 138 },
  { label: "Shadow Modified Foot Guards", tt: 69 },
  { label: "Shadow Modified Gloves", tt: 69 },
  { label: "Shadow Modified Harness", tt: 207 },
  { label: "Shadow Modified Helmet", tt: 151 },
  { label: "Shadow Modified Shin Guards", tt: 69 },
  { label: "Shadow Modified Thigh Guards", tt: 138 },
  { label: "Shadow Shin Guards", tt: 51 },
  { label: "Shadow Shin Guards (L)", tt: 51 },
  { label: "Shadow Shin Guards, SGA Edition", tt: 51 },
  { label: "Shadow Thigh Guards", tt: 102 },
  { label: "Shadow Thigh Guards (L)", tt: 102 },
  { label: "Shadow Thigh Guards, SGA Edition", tt: 102 },
  { label: "Shin Guards of the Wormslayer", tt: 88 },
  { label: "Shogun Arm Guards", tt: 25.5 },
  { label: "Shogun Arm Guards, SGA Edition", tt: 25.5 },
  { label: "Shogun Face Guard", tt: 12.75 },
  { label: "Shogun Face Guard, SGA Edition", tt: 12.75 },
  { label: "Shogun Foot Guards", tt: 12.75 },
  { label: "Shogun Foot Guards, SGA Edition", tt: 12.75 },
  { label: "Shogun Gloves", tt: 12.75 },
  { label: "Shogun Gloves, SGA Edition", tt: 12.75 },
  { label: "Shogun Harness", tt: 38.25 },
  { label: "Shogun Harness, SGA Edition", tt: 38.25 },
  { label: "Shogun Harness Improved", tt: 67.5 },
  { label: "Shogun Shin Guards", tt: 12.75 },
  { label: "Shogun Shin Guards, SGA Edition", tt: 12.75 },
  { label: "Shogun Thigh Guards", tt: 25.5 },
  { label: "Shogun Thigh Guards, SGA Edition", tt: 25.5 },
  { label: "Shogun Thigh Guards Improved", tt: 39.7 },
  { label: "Sigyn Arm Guards", tt: 115 },
  { label: "Sigyn Foot Guards", tt: 70 },
  { label: "Sigyn Gloves", tt: 70 },
  { label: "Sigyn Harness", tt: 155 },
  { label: "Sigyn Helmet", tt: 90 },
  { label: "Sigyn Shin Guards", tt: 110 },
  { label: "Sigyn Thigh Guards", tt: 120 },
  { label: "Silverstitch Arm Guards", tt: 5.7 },
  { label: "Silverstitch Foot Guards", tt: 5.7 },
  { label: "Silverstitch Hand Guards", tt: 5.7 },
  { label: "Silverstitch Harness", tt: 5.7 },
  { label: "Silverstitch Head Cover", tt: 5.7 },
  { label: "Silverstitch Leg Guards", tt: 5.7 },
  { label: "Silverstitch Shin Guards", tt: 5.7 },
  { label: "Solir Arm Guards (L)", tt: 117.5 },
  { label: "Solir Foot Guards (L)", tt: 117.5 },
  { label: "Solir Gloves (L)", tt: 117.5 },
  { label: "Solir Harness (L)", tt: 156 },
  { label: "Solir Helmet (L)", tt: 79.5 },
  { label: "Solir Shin Guards (L)", tt: 119 },
  { label: "Solir Thigh Guards (L)", tt: 122 },
  { label: "Spam Arm Guards (L)", tt: 100 },
  { label: "Spam Foot Guards (L)", tt: 50 },
  { label: "Spam Gloves (L)", tt: 50 },
  { label: "Spam Harness (L)", tt: 150 },
  { label: "Spam Helmet (L)", tt: 50 },
  { label: "Spam Shin Guards (L)", tt: 50 },
  { label: "Spam Thigh Guards (L)", tt: 100 },
  { label: "Spartacus Arm Guards (L)", tt: 126 },
  { label: "Spartacus Back Strap (L)", tt: 181.2 },
  { label: "Spartacus Foot Guards (L)", tt: 121.2 },
  { label: "Spartacus Gloves (L)", tt: 121.2 },
  { label: "Spartacus Groin Guard (L)", tt: 130.8 },
  { label: "Spartacus Head Piece (L)", tt: 130.8 },
  { label: "Spartacus Helmet (L)", tt: 130.8 },
  { label: "Spartacus Shin Guards (L)", tt: 132 },
  { label: "Spartacus Shoulder Guard (L)", tt: 181.2 },
  { label: "Special Issue arm-guards (L)", tt: 0.52 },
  { label: "Special Issue face-guard (L)", tt: 0.34 },
  { label: "Special Issue foot guards (L)", tt: 0.27 },
  { label: "Special Issue gloves (L)", tt: 0.27 },
  { label: "Special Issue harness (L)", tt: 0.74 },
  { label: "Special Issue shin-guards (L)", tt: 0.34 },
  { label: "Special Issue thigh-guards (L)", tt: 0.52 },
  { label: "Special Ops Arm Guards (C,L)", tt: 126 },
  { label: "Special Ops Foot Guards (C,L)", tt: 121.2 },
  { label: "Special Ops Gloves (C,L)", tt: 121.2 },
  { label: "Special Ops Harness (C,L)", tt: 181 },
  { label: "Special Ops Harness (L)", tt: 181 },
  { label: "Special Ops Helmet (C,L)", tt: 130.8 },
  { label: "Special Ops Shin Guards (C,L)", tt: 132 },
  { label: "Special Ops Thigh Guards (C,L)", tt: 130.8 },
  { label: "Spectre Arm Guards (L)", tt: 88 },
  { label: "Spectre Face Mask (L)", tt: 85 },
  { label: "Spectre Foot Guards (L)", tt: 86 },
  { label: "Spectre Gloves (L)", tt: 86 },
  { label: "Spectre Harness (L)", tt: 116 },
  { label: "Spectre Shin Guards (L)", tt: 90 },
  { label: "Spectre Thigh Guards (L)", tt: 89 },
  { label: "Stealth Arm Guards (C,L)", tt: 66 },
  { label: "Stealth Arm Guards (L)", tt: 66 },
  { label: "Stealth Foot Guards (C,L)", tt: 66 },
  { label: "Stealth Foot Guards (L)", tt: 66 },
  { label: "Stealth Gloves (C)(L)", tt: 66 },
  { label: "Stealth Gloves (L)", tt: 66 },
  { label: "Stealth Harness (C,L)", tt: 110 },
  { label: "Stealth Harness (L)", tt: 110 },
  { label: "Stealth Helmet (C,L)", tt: 59.2 },
  { label: "Stealth Helmet (L)", tt: 59.2 },
  { label: "Stealth Shin Guards (C,L)", tt: 55 },
  { label: "Stealth Shin Guards (L)", tt: 55 },
  { label: "Stealth Thigh Guards (C,L)", tt: 64.5 },
  { label: "Stealth Thigh Guards (L)", tt: 64.5 },
  { label: "Stolen Imperium Arm Guards", tt: 28 },
  { label: "Stolen Imperium Cap", tt: 30 },
  { label: "Stolen Imperium Chest Guard", tt: 30 },
  { label: "Stolen Imperium Foot Guards", tt: 28 },
  { label: "Stolen Imperium Hand Guards", tt: 28 },
  { label: "Stolen Imperium Shin Guards", tt: 28 },
  { label: "Stolen Imperium Thigh Guards", tt: 28 },
  { label: "Supremacy Arm Guards", tt: 298 },
  { label: "Supremacy Arm Guards (L)", tt: 298 },
  { label: "Supremacy Arm Guards, SGA Edition", tt: 298 },
  { label: "Supremacy Foot Guards", tt: 287 },
  { label: "Supremacy Foot Guards (L)", tt: 287 },
  { label: "Supremacy Foot Guards, SGA Edition", tt: 287 },
  { label: "Supremacy Gloves", tt: 287 },
  { label: "Supremacy Gloves (L)", tt: 287 },
  { label: "Supremacy Gloves, SGA Edition", tt: 287 },
  { label: "Supremacy Harness", tt: 354 },
  { label: "Supremacy Harness (L)", tt: 354 },
  { label: "Supremacy Harness, SGA Edition", tt: 354 },
  { label: "Supremacy Helmet", tt: 298 },
  { label: "Supremacy Helmet (L)", tt: 298 },
  { label: "Supremacy Helmet, SGA Edition", tt: 298 },
  { label: "Supremacy Shin Guards", tt: 311 },
  { label: "Supremacy Shin Guards (L)", tt: 311 },
  { label: "Supremacy Shin Guards, SGA Edition", tt: 311 },
  { label: "Supremacy Thigh Guards", tt: 309 },
  { label: "Supremacy Thigh Guards (L)", tt: 309 },
  { label: "Supremacy Thigh Guards, SGA Edition", tt: 309 },
  { label: "Thigh Guards of the Wormslayer", tt: 153 },
  { label: "Thorifoid Berserker's Helm (L)", tt: 86 },
  { label: "Thorifoid Berserker's Helm Flimsy (L)", tt: 34 },
  { label: "Thorifoid Berserker's Helm Superior", tt: 90 },
  { label: "Thunderbird Arm Guards", tt: 115 },
  { label: "Thunderbird Arm Guards (L)", tt: 115 },
  { label: "Thunderbird Foot Guards", tt: 70 },
  { label: "Thunderbird Foot Guards (L)", tt: 70 },
  { label: "Thunderbird Gloves", tt: 70 },
  { label: "Thunderbird Gloves (L)", tt: 70 },
  { label: "Thunderbird Harness", tt: 155 },
  { label: "Thunderbird Harness (L)", tt: 155 },
  { label: "Thunderbird Helmet", tt: 90 },
  { label: "Thunderbird Helmet (L)", tt: 90 },
  { label: "Thunderbird Shin Guards", tt: 120 },
  { label: "Thunderbird Shin Guards (L)", tt: 120 },
  { label: "Thunderbird Thigh Guards", tt: 110 },
  { label: "Thunderbird Thigh Guards (L)", tt: 110 },
  { label: "Tiger Arm Guards", tt: 102.2 },
  { label: "Tiger Arm Guards (L)", tt: 102.2 },
  { label: "Tiger Foot Guards", tt: 83 },
  { label: "Tiger Foot Guards (L)", tt: 83 },
  { label: "Tiger Gloves", tt: 83 },
  { label: "Tiger Gloves (L)", tt: 83 },
  { label: "Tiger Harness", tt: 134.3 },
  { label: "Tiger Harness (L)", tt: 134.3 },
  { label: "Tiger Helmet", tt: 89.4 },
  { label: "Tiger Helmet (L)", tt: 89.4 },
  { label: "Tiger Shin Guards", tt: 91.2 },
  { label: "Tiger Shin Guards (L)", tt: 91.2 },
  { label: "Tiger Thigh Guards", tt: 97.8 },
  { label: "Tiger Thigh Guards (L)", tt: 97.8 },
  { label: "Trojan Breastplate", tt: 7 },
  { label: "Trooper Arm Guards", tt: 24 },
  { label: "Trooper Foot Guards", tt: 22 },
  { label: "Trooper Gloves", tt: 22 },
  { label: "Trooper Harness", tt: 40 },
  { label: "Trooper Helmet", tt: 21.5 },
  { label: "Trooper Shin Guards", tt: 20 },
  { label: "Trooper Thigh Guards", tt: 23.5 },
  { label: "Turrelion Arm Guards", tt: 2.2 },
  { label: "Turrelion Foot Guards", tt: 2.2 },
  { label: "Turrelion Gloves", tt: 2.2 },
  { label: "Turrelion Harness", tt: 2.2 },
  { label: "Turrelion Homeland Arm Guards", tt: 14.4 },
  { label: "Turrelion Homeland Face Guard", tt: 72 },
  { label: "Turrelion Homeland Foot Guards", tt: 36.6 },
  { label: "Turrelion Homeland Hand Guards", tt: 36.6 },
  { label: "Turrelion Homeland Harness", tt: 72 },
  { label: "Turrelion Homeland Shin Guards", tt: 14.4 },
  { label: "Turrelion Homeland Thigh Guards", tt: 36.6 },
  { label: "Turrelion Leg Guards", tt: 2.2 },
  { label: "Turrelion Mask", tt: 2.2 },
  { label: "Turrelion Shin Guards", tt: 2.2 },
  { label: "Unique Carramone Arm Guards", tt: 280 },
  { label: "Unique Carramone Foot Guards", tt: 490 },
  { label: "Unique Carramone Gloves", tt: 490 },
  { label: "Unique Carramone Harness", tt: 480 },
  { label: "Unique Carramone Shin Guards", tt: 390 },
  { label: "Unique Carramone Thigh Guards", tt: 370 },
  { label: "Unique Lady Kraster Helmet (F)", tt: 195 },
  { label: "Unique Lord Kraster Helmet (M)", tt: 195 },
  { label: "Ursa Arm Guards", tt: 90 },
  { label: "Ursa Arm Guards (L)", tt: 84 },
  { label: "Ursa Foot Guards", tt: 66 },
  { label: "Ursa Foot Guards (L)", tt: 72 },
  { label: "Ursa Gloves", tt: 54 },
  { label: "Ursa Gloves (L)", tt: 60 },
  { label: "Ursa Harness", tt: 144 },
  { label: "Ursa Harness (L)", tt: 144 },
  { label: "Ursa Helmet", tt: 78 },
  { label: "Ursa Helmet (L)", tt: 78 },
  { label: "Ursa Shin Guards", tt: 84 },
  { label: "Ursa Shin Guards (L)", tt: 78 },
  { label: "Ursa Thigh Guards", tt: 84 },
  { label: "Ursa Thigh Guards (L)", tt: 84 },
  { label: "Vain Arm Guards", tt: 225 },
  { label: "Vain Arm Guards (L)", tt: 225 },
  { label: "Vain Foot Guards", tt: 205 },
  { label: "Vain Foot Guards (L)", tt: 205 },
  { label: "Vain Gloves", tt: 205 },
  { label: "Vain Gloves (L)", tt: 205 },
  { label: "Vain Harness", tt: 320 },
  { label: "Vain Harness (L)", tt: 320 },
  { label: "Vain Helmet", tt: 175 },
  { label: "Vain Helmet (L)", tt: 175 },
  { label: "Vain Shin Guards", tt: 210 },
  { label: "Vain Shin Guards (L)", tt: 210 },
  { label: "Vain Thigh Guards", tt: 225 },
  { label: "Vain Thigh Guards (L)", tt: 225 },
  { label: "Valiant Arm Guards", tt: 8.1 },
  { label: "Valiant Face Guard", tt: 6 },
  { label: "Valiant Foot Guards", tt: 5.9 },
  { label: "Valiant Gloves", tt: 5.9 },
  { label: "Valiant Harness", tt: 12 },
  { label: "Valiant Shin Guards", tt: 5.8 },
  { label: "Valiant Thigh Guards", tt: 8.4 },
  { label: "Vampire Arm Guards", tt: 12 },
  { label: "Vampire Face Guard", tt: 9.1 },
  { label: "Vampire Foot Guards", tt: 9 },
  { label: "Vampire Gloves", tt: 9 },
  { label: "Vampire Harness", tt: 20 },
  { label: "Vampire Shin Guards", tt: 9.2 },
  { label: "Vampire Thigh Guards", tt: 13 },
  { label: "Viceroy Arm Guards", tt: 60 },
  { label: "Viceroy Arm Guards Adjusted", tt: 60 },
  { label: "Viceroy Arm Guards Adjusted - Skullcandy Edition", tt: 60 },
  { label: "Viceroy Arm Guards Modified", tt: 60 },
  { label: "Viceroy Arm Guards Modified - Skullcandy Edition", tt: 60 },
  { label: "Viceroy Arm Guards - Skullcandy Edition", tt: 60 },
  { label: "Viceroy Foot Guards", tt: 44 },
  { label: "Viceroy Foot Guards Adjusted", tt: 44 },
  { label: "Viceroy Foot Guards Modified", tt: 44 },
  { label: "Viceroy Foot Guards Modified - Skullcandy Edition", tt: 44 },
  { label: "Viceroy Foot Guards - Skullcandy Edition", tt: 44 },
  { label: "Viceroy Gloves", tt: 36 },
  { label: "Viceroy Gloves Adjusted", tt: 36 },
  { label: "Viceroy Gloves Guards - Skullcandy Edition", tt: 36 },
  { label: "Viceroy Gloves Improved", tt: 36 },
  { label: "Viceroy Gloves Modified", tt: 36 },
  { label: "Viceroy Gloves Modified - Skullcandy Edition", tt: 36 },
  { label: "Viceroy Harness", tt: 96 },
  { label: "Viceroy Harness Adjusted", tt: 96 },
  { label: "Viceroy Harness Adjusted - Skullcandy Edition", tt: 96 },
  { label: "Viceroy Harness Guards - Skullcandy Edition", tt: 96 },
  { label: "Viceroy Harness Improved", tt: 96 },
  { label: "Viceroy Harness Modified", tt: 96 },
  { label: "Viceroy Harness Modified - Skullcandy Edition", tt: 96 },
  { label: "Viceroy Helmet", tt: 52 },
  { label: "Viceroy Helmet Adjusted", tt: 52 },
  { label: "Viceroy Helmet Adjusted - Skullcandy Edition", tt: 52 },
  { label: "Viceroy Helmet Guards - Skullcandy Edition", tt: 52 },
  { label: "Viceroy Helmet Modified", tt: 52 },
  { label: "Viceroy Helmet Modified - Skullcandy Edition", tt: 52 },
  { label: "Viceroy Shin Guards", tt: 56 },
  { label: "Viceroy Shin Guards Adjusted", tt: 56 },
  { label: "Viceroy Shin Guards Modified", tt: 56 },
  { label: "Viceroy Shin Guards Modified - Skullcandy Edition", tt: 56 },
  { label: "Viceroy Shin Guards - Skullcandy Edition", tt: 56 },
  { label: "Viceroy Thigh Guards", tt: 56 },
  { label: "Viceroy Thigh Guards Adjusted", tt: 56 },
  { label: "Viceroy Thigh Guards Modified", tt: 56 },
  { label: "Viceroy Thigh Guards Modified - Skullcandy Edition", tt: 56 },
  { label: "Viceroy Thigh Guards - Skullcandy Edition", tt: 56 },
  { label: "Vigilante Arm Guards", tt: 38.5 },
  { label: "Vigilante Arm Guards, SGA Edition", tt: 38.5 },
  { label: "Vigilante Arm Guards Adjusted", tt: 38.5 },
  { label: "Vigilante Arm Guards Modified", tt: 38.5 },
  { label: "Vigilante Foot Guards", tt: 19.25 },
  { label: "Vigilante Foot Guards, SGA Edition", tt: 19.25 },
  { label: "Vigilante Foot Guards Adjusted", tt: 19.25 },
  { label: "Vigilante Foot Guards Modified", tt: 19.25 },
  { label: "Vigilante Gloves", tt: 19.25 },
  { label: "Vigilante Gloves, SGA Edition", tt: 19.25 },
  { label: "Vigilante Gloves Adjusted", tt: 19.25 },
  { label: "Vigilante Gloves Modified", tt: 19.25 },
  { label: "Vigilante Harness", tt: 57.75 },
  { label: "Vigilante Harness, SGA Edition", tt: 57.75 },
  { label: "Vigilante Harness Adjusted", tt: 57.75 },
  { label: "Vigilante Harness Augmented", tt: 94.5 },
  { label: "Vigilante Harness Modified", tt: 57.75 },
  { label: "Vigilante Helmet", tt: 19.25 },
  { label: "Vigilante Helmet, SGA Edition", tt: 19.25 },
  { label: "Vigilante Helmet Adjusted", tt: 19.25 },
  { label: "Vigilante Helmet Modified", tt: 19.25 },
  { label: "Vigilante Shin Guards", tt: 19.25 },
  { label: "Vigilante Shin Guards, SGA Edition", tt: 19.25 },
  { label: "Vigilante Shin Guards Adjusted", tt: 19.25 },
  { label: "Vigilante Shin Guards Modified", tt: 19.25 },
  { label: "Vigilante Thigh Guards", tt: 38.5 },
  { label: "Vigilante Thigh Guards, SGA Edition", tt: 38.5 },
  { label: "Vigilante Thigh Guards Adjusted", tt: 38.5 },
  { label: "Vigilante Thigh Guards Augmented", tt: 63 },
  { label: "Vigilante Thigh Guards Modified", tt: 38.5 },
  { label: "Viking Arm Guards", tt: 100 },
  { label: "Viking Foot Guards", tt: 50 },
  { label: "Viking Gloves", tt: 50 },
  { label: "Viking Harness", tt: 140 },
  { label: "Viking Helmet", tt: 80 },
  { label: "Viking Shin Guards", tt: 100 },
  { label: "Viking Thigh Guards", tt: 95 },
  { label: "Vindicator Arm Guards", tt: 21 },
  { label: "Vindicator Face Guard", tt: 14 },
  { label: "Vindicator Foot Guards", tt: 17 },
  { label: "Vindicator Gloves", tt: 17 },
  { label: "Vindicator Harness", tt: 34 },
  { label: "Vindicator Shin Guards", tt: 15 },
  { label: "Vindicator Thigh Guards", tt: 19.5 },
  { label: "Wannabe Arm Guards (L)", tt: 3.2 },
  { label: "Wannabe Face Guard (L)", tt: 2.8 },
  { label: "Wannabe Foot Guards (L)", tt: 1.8 },
  { label: "Wannabe Gloves (L)", tt: 1.8 },
  { label: "Wannabe Harness (L)", tt: 4.4 },
  { label: "Wannabe Shin Guards (L)", tt: 2.8 },
  { label: "Wannabe Thigh Guards (L)", tt: 3.2 },
  { label: "Warrior Arm Guards", tt: 12 },
  { label: "Warrior Face Guard", tt: 6 },
  { label: "Warrior Foot Guards", tt: 5.92 },
  { label: "Warrior Gloves", tt: 5.92 },
  { label: "Warrior Harness", tt: 17.77 },
  { label: "Warrior Shin Guards", tt: 5.92 },
  { label: "Warrior Thigh Guards", tt: 11.85 },
  { label: "XFire Survival Arm Guards (L)", tt: 48 },
  { label: "XFire Survival Foot Guards (L)", tt: 48 },
  { label: "XFire Survival Gloves (L)", tt: 48 },
  { label: "XFire Survival Harness (L)", tt: 79 },
  { label: "XFire Survival Helmet (L)", tt: 43 },
  { label: "XFire Survival Shin Guards (L)", tt: 40 },
  { label: "XFire Survival Thigh Guards (L)", tt: 47 },
  { label: "Zeraf Armor Arm Guards (L)", tt: 2.5 },
  { label: "Zeraf Armor Gloves (L)", tt: 4.5 },
  { label: "Zeraf Armor Harness (L)", tt: 6 },
  { label: "Zombie Arm Guards", tt: 60 },
  { label: "Zombie Arm Guards (L)", tt: 40 },
  { label: "Zombie Face Guard", tt: 40 },
  { label: "Zombie Face Guard (L)", tt: 40 },
  { label: "Zombie Foot Guards", tt: 39 },
  { label: "Zombie Foot Guards (L)", tt: 39 },
  { label: "Zombie Gloves", tt: 39 },
  { label: "Zombie Gloves (L)", tt: 39 },
  { label: "Zombie Harness", tt: 70 },
  { label: "Zombie Harness (L)", tt: 70 },
  { label: "Zombie Shin Guards", tt: 38 },
  { label: "Zombie Shin Guards (L)", tt: 38 },
  { label: "Zombie Thigh Guards", tt: 39 },
  { label: "Zombie Thigh Guards (L)", tt: 39 }
];
export default suggestions;
